### ISSUE TITLE
Open tree when editing resource

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#10265]
sottwell created Redmine issue ID 10265

Would it be possible to have a way to open the Tree to the resource's location, perhaps when clicking on the resource's title at the top of the editing page?

**Comment by jpdevries** [comment]
Have a client 2.3.5 who's tree always closes when they save or go to a new resource. It doesn't remember where it was. I believe this may be content related because according to them it just stopped working one day. The site has 5 contexts and nearly 7,000 resources.

This seems like the closest open issue so noting it here.

**Comment by alroniks** [comment]
Closed in favor of #14768
