### ISSUE TITLE
Coherence in table names

### ISSUE THREAD

**Issue by frenchfries** [modxcms/revolution#10596]
frenchfries created Redmine issue ID 10596

As those tables,
modx_system_settings
modx_user_settings modx_context_setting
should be
modx_akesse_context_settingS .

**Comment by jpdevries** [comment]
I think it would be nice if we used microformats for things like user info and addresses. For example "familyname" instead of "lastname" and "givenname" instead of "firstname".

**Comment by mrhaw** [comment]
A small comment on that - firstname and lastname is what is being used in international english. Not that I care or criticize a change.

**Comment by OptimusCrime** [comment]
What is microformats?

**Comment by sottwell** [comment]
http://microformats.org/
https://github.com/indieweb/php-mf2

**Comment by OptimusCrime** [comment]
Isn't that concerning how the HTML output is formatted, and not the underlying column names?

**Comment by sottwell** [comment]
Well, yes and no. The issue is should this concept be supported at the lowest levels? If the database table and field names reflect some kind of standard, then it's far easier to automate the process of the controllers when generating the views. Of course, the question is, what standard? And what happens when the chosen standard changes or for some other reason isn't desirable? 

This could be the purview of the controller layer - whatever fetches the data and organizes it for processing and output. Or it could be left up to the ultimate designer to translate the model to his view, which is less than helpful.

A MODX-classic example is the site_content's 'introtext' field. In the editing forms, it's labelled as 'Summary'. So somebody trying to use the [[*summary]] tag is going to have a problem. This is more a problem of presentation, but still, somebody should have done a bit more consideration the values of consistency. And yes, the actual field label is 'Summary (introtext)'. Three guesses who nagged and kvetched until that '(introtext)' bit got added...

**Comment by OptimusCrime** [comment]
Well, I guess that is a fair point, but there are endless examples of column names not matching the "friendly name" in various APIs and UIs. 

The summary/introtext problem is really another issue, as the two names does not mean the same. Introtext is found between the title and the content, usually in a bigger font than the content. Summary is, well, a summary. The two does not correlate one-to-one. 

However, my argument is that what the database field is called is irrelevant in the underlying implementation seen in context of users only using the `[[*introtext]]` or `[[*summary]]` placeholders.

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/14313

**Comment by sergant210** [comment]
Tables "membergroup_names", "member_groups" for user groups. And the next tables "user_group_role" and  "user_group_settings" for user groups too.
Table "documentgroup_names" for resource groups. And table "access_resource_groups" for permissions.

**Comment by theboxer** [comment]
I can't imagine we're changing tables names i the current state, as it'd be huge breaking change.
