### ISSUE TITLE
[2.2] Loading a lexicon in specific language via API fails

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#11240]
I think there is something wrong with the lexicon! Try this in a snippet:

```
$modx->lexicon->load('en:core:about');
echo $modx->lexicon('about_msg');
```

This will return NULL. You have to set a cultureKey first to make it work:

```
$modx->setOption('cultureKey', 'en');
$modx->lexicon->load('core:about');
echo $modx->lexicon('about_msg');
```

This behaviour seems to be new or a bug – since Bob (book page 350) and RTFM (http://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/internationalization) are saying that `$modx->lexicon->load('en:core:about')` works.
There is a forum post on this, too: http://forums.modx.com/thread/89821/getting-a-value-from-the-lexicon

**Comment by christianseel** [comment]
I took a look into the code: this is the expected behavior. `$modx->lexicon->load('en:core:about')` works perfectly as expected and loads the correct language, but the `$modx->lexicon('about_msg')` is always referring to the current `cultureKey` setting if you do not specify your disired language in the `$modx->lexicon()` call.

So this is how the syntax is correct:
```
$modx->lexicon->load('fr:core:about');
return $modx->lexicon('about_msg', array(), 'fr');
```

This is the function signature:
```
/**
     * Grabs a processed lexicon string.
     *
     * @access public
     * @param string $key
     * @param array $params
     * @param string $language
     * @return null|string The translated string, or null if none is set
     */
    public function lexicon($key,$params = array(),$language = '') {}
```
#modxbughunt

@modxbot close
