### ISSUE TITLE
Active Permissions in Access Policies are not synced with Policy Templates

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#11361]
If a Permission (no matter if custom or standard, try for example "database") is removed from a policy template, access policies that had this permission checked before it was removed still display the number of active permissions as of before deleting one from the template, e.g. if I delete "database" from the policy template AdministratorTemplate, the Administrator access policy now displays "172 of 171" (the entry is still in the data array of the permission) and when "database" is re-added again it is also already ticked/activated...don't think this is intentional, right? =)

To fix probably somewhere near: core/model/modx/processors/security/access/policy/template/update.class.php

Tested in 2.2.14pl traditional

**Comment by achterbahn** [comment]
I tried but could not reproduce this on MODX Revolution 2.5.4-pl (sdk). 

1. Used "AdministratorTemplate" in ACL Policy Templates (total 174 entries)
2. Deleted one permission  (e.g. "about"), save, refresh -> total 173
3. Access Policies reports "173 of 173"
4. Re-added "about" permission to template, save, refresh -> total 174
5. Access Policies reports "173 of 174" -> "about" is not ticked

Seems the problem is solved. Or did I misunderstand the issue?

**Comment by jgulledge19** [comment]
#modxbughunt Close
@achterbahn Did the same on 2.5.5pl and don't see the issue.
