### ISSUE TITLE
Saves hang with form in rich text editor

### ISSUE THREAD

**Issue by electrickite** [modxcms/revolution#11877]
Creating a form with a submit button in a rich text editor causes MODX to hang during saves.

This only occurs using a WYSIWYG editor that renders markup in the content area, like Redactor. TinyMCE strips out the `<form>`opening and closing tags, avoiding the issue. This has been observed in Revo 2.2 and 2.3.

Steps to reproduce:

  1. Install a rich text editor that does not strip form elements (such as Redactor)
  2. Create a new document and enable rich text editing
  3. Create a form in the content area with the following markup: `<form><button type="submit" name="Submit" id="submit" class="button radius">Submit</button></form>`
  4. Toggle away from  "code view" or similar so the form button is rendered in the content area
  5. Click the Save button to save the resource.
  6. Observe that the save never completes and the following message is logged to the browser console: `TypeError: '[object HTMLButtonElement]' is not a function (evaluating 'm.submit()')`

**Comment by Mark-H** [comment]
The problem with this - and I've seen it too, and think we have an open issue for it - is actually the `<button id="submit">` I think. That ID is replacing the submit handler somehow. 

I do think this is an issue to solve in Redactor (and other editors if they have the same problem) rather than core.
