### ISSUE TITLE
Users sudo option should be removed. It's weird!

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#12169]
This sudo options causes a lot of weird permission issues. Also it's a weird option, because we already have permission. It happens a lot that users need to have the sudo option to have some permissions while the permissions itself are assigned to the group where the user belongs to.

In my opinion the sudo option can be removed totally. When a user(group) has the permission, it should be allowed. With or without the sudo. So it's not needed.

**Comment by Mark-H** [comment]
Agreed with Romain. The OP describes an issue with ACLs that is worked around by sudo, not an issue with sudo itself. When a user has the right permission, it doesn't matter if sudo is enabled or not. Sounds more like a certain permission is missing :)

**Comment by bertoost** [comment]
No it was not the permissions. I found out that $modx->hasPermission() also accepts an array for checking multiple permissions. Unfortunate this wasn't described in the docs and I thought it was just an simple array, as in array('permission_1', 'permission_2').. But I found that I should apply "true" to them as well. So; array('permission_1' => true, 'permission_2' => true)
The missing of "true" could be avoid to enable sudo. This was a missunderstanding of the hasPermission(). I have updated the docs too.

This way the sudo options works as expected, but I think we should only stay at permissions and not adding features to skip a proper ACL setup.

**Comment by Mark-H** [comment]
Great, so sudo allowed to bypass an incorrectly configured set of permissions (in this case, a set of permissions being checked incorrectly, rather than policies being set wrong). In other words, sudo did exactly what it is supposed to do!

Bert's last post suggests that hasPermission is lacking docs or sanity checking related to providing an array of permissions. 

Sudo is working as expected. 

So the _actual problem_ should be fixed, not a useful feature removed. 

[From wuuti](https://github.com/modxcms/revolution/issues/12169#issuecomment-64181026):
> The sudo seems to be legacy from a time when permissions were not complete (are they now?)

That's an incorrect assumption. Sudo was added after ACLs (2.2-ish), and not because "permissions were not complete", but because it allowed a full admin user to prevent getting locked out. Which is especially useful when working on setting up more restricted ACLs. 

Sudo is not perfect, but removing it is most definitely not the answer.

**Comment by wuuti** [comment]
@Mark-H I understand your arguments here, but it should be noted that in this discussion there was a strong tendency for removing the sudo option. I would love to continue the general discussion (why not here, the issue was general as well originally).

From my point of view the sudo leads a lot of (even expierenced) MODX developers to always work with an administrator with sudo rights, and additionally, making client accounts work with that simply to bypass any permission related problems. I did that as well in the past, as well as having way too many permissions in the client's policy templates. Why? Because it eases your life, if you and your clients are not bothered with an annoying "Permission denied" alert (where you even can't see, which permission is missing where). Thats all related to the fact, that the permission system in MODX is powerful, but complex to setup correctly (and efficiently). 

That leads me to the following, each bullet point worth a separate issue, some of them easy, some quite complex to solve: 

* **there is no preconfigured _Editor_ group with a fitting policy** stripped of everything used only by developers or admins. _If this was in the setup as default_, a lot of work (and frustration) could be saved, and we could establish a baselined and correct ACL based setup for every installation. 
* **error messages for denied permissions are currently useless**. Even the log lines do not give you the missing permission nor the context where this was raised. _The logs should include that information_ (think there is already an issue or PR for that).
* when setting up a policy, **you have to opt-out every permission you don't want** the user to have instead of _giving the user the permissions he needs (opt-in)._ (not to mention that the templates by default contain hundreds of permissions, which you may have to click away)
* **permissions are, all in all, not well documented** - you don't know where they are used and if you need them or to achieve what behaviour. 
* as was stated, the sudo option is to bypass a broken setup. It should not be activated by default, even not for the initial admin account. **Instead, sudo should only be activated in case a problem has to be fixed**, and maybe _automatically get deactivated after a period of time or the sudo user logs out._
* **any user able to manage users can give sudo rights and therefore bypass anything**. So you can elevate your privileges easily. We should have at least something like a 'make_users_sudo' permission, and this should be applied only to dedicated accounts (like initial admin).  
* **the sudo checkbox should not be availabe in the users management UI. ** (unless at least you have the former permission). If we only need sudo in cases where something is broken, it should be ok to _activate that by editing the database or by other means_ (login with a special, one time sudo-hash?)
* **setting up an ACL-based system is to complicated**. We need more _wizard-style ways_ to setup things for a group, which would help also MODX Experts to avoid errors there. 
* **there is no overview table which permissions a user finally has**. It is often hard to see which permissions are finally computed for a user, they are unioned from a lot of policies - and removing a permission from one policy does not guarantee that this permission is not still included in another. 
* **you can only give permissions, not deny a permission**. It would be great to have the possibility to _deny_ certain permissions completely, regardless of how many policies have included them.  

What's your opinion here?

**Comment by sottwell** [comment]
I had always presumed that the sudo user, like UNIX root, was not intended to be generally used. You never allow root to have ssh login. Every user has his own user account, and only uses sudo for brief root access to perform a specific action, then exits from the root account back to his own account.

In the case of MODX, it makes sense that the initial user would be sudo, but there should not be any other sudo users. That sudo account should only be logged into by well-trusted admins for a specific purpose, then the user should log out and log in again as his usual Manager user.

Perhaps a true sudo would be better - the ability to switch users on-the-fly, and the sudo user account would not be able to log in?

**Comment by Mark-H** [comment]
Like you say yourself, those bullet points are all worth _separate issues_, and some of them already do have one probably. I agree most of them should be solved. Non-sudo users being able to grant themselves sudo is my biggest problem.

The reason I closed this though, is that none of your bullet points, and very few other posts in this thread, actually deal with the idea of _removing_ sudo, only improving the ACLs systems, including sudo, which you yourself state is useful.

**Comment by pyrographics** [comment]
I believe there should always be at least one user who can never be locked out if someone messes up their ACL's.  Why not just lock Administrator ACLs so they cannot be edited by a user like snippet options are locked?  Make the user unlock them before editing and warn them of the consequences.
