### ISSUE TITLE
Top Menu drag and drop not functioning correctly

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#12231]
I have a lot of items that were in different categories, which don't appear on the top menu after a default upgrade.  I've tested on a couple different installs / servers, and when I try to move more than one menu item in a session, it only seems to save the last change that I made. 

_Example:_ 

I set up two quick links for commonly edited pages. First I move "Edit Lunch Menu" to the "Content" folder, then I move "Edit Pizza Menu" just below it.  I click on the dashboard, hover over "Content" and the only item that has moved is "Edit Pizza Menu".

**Comment by rtripault** [comment]
Hi @matdave 

Could you please confirm this happens on Revo 2.3.2+ ?
Some changes occurred in the way ajax requests are done, which should fix that issue.

Thanks

**Comment by matdave** [comment]
Correct, I am using Revo 2.3.2 on a couple different Apache servers. It is only affected when I use the drag and drop multiple times.

**Comment by rtripault** [comment]
OK, this is mostly likely because each "sort" (drag/drop) send the whole tree structure and iterate over each node to update their parent (see https://github.com/modxcms/revolution/blob/develop/core/model/modx/processors/system/menu/sort.class.php).

This process can take some time, so if you reorder multiple entries "too" fast, first records might not be "updated" yet in the tree, resulting in subsequent "sorts" sending the old tree structure.

To help you "handle that bug", there should be some kind of visual indication that your "sort" occurred : a "glowing rectangle" around your moved tree node should appear when the operation succeed.

Note that it could take a really long time with a "huge" tree : more than 12s. here with a 120 nodes tree.

To handle faster processing, my guess would be that we should only send the new node parent to the sort processor instead of the whole tree...

Hope my explanation attempt makes sense :smile:
