### ISSUE TITLE
[2.3.2] Unable to update recaptcha system settings keys

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/revolution#12281]
### Summary
Unable to update `recaptcha.private_key` and `recaptcha.public_key` keys in system settings. 
This issue was previously reported here: https://github.com/modxcms/revolution/issues/6208

### Step to reproduce
Go to System Settings, search by key: `recaptcha`. Edit the values of those two fields.

### Observed behavior
The value fields are reset (autocleared) when they lose focus. The update isn't recorded.

I should note that the namespace for those settings is set to 'recaptcha', but no such namespace exists in the system.

I should also add that the Formit recaptcha value fields behave normally when updated. This issue doens't concern them.

### Expected behavior
The values should be saved and remain visible in the fields.

### Environment
MODX 2.3.2, PHP 5.3.29, mysql 5.1.72, Latest builds of CHROME/FF/SAFARI

**Comment by pixelchutes** [comment]
When saving (change focus), do you see anything of interest on the Network tab in the browser's developer tools? Any errors, etc?

**Comment by beau-gosse** [comment]
No apparent error to report. The server is returning a status 200 for index.php (POST) and 304 for dirty.gif (GET).

**Comment by rtripault** [comment]
Just confirming the issue, but that's not a Revolution one, but [Login](https://github.com/modxcms/Login/issues) (may i suggest to open the issue there ?).

The error is due to the fact "Login" package does not create any "recaptcha" namespace, which is required (see [related code](https://github.com/modxcms/revolution/blob/master/core/model/modx/processors/system/settings/update.class.php#L51-54)).
My suggestion would be to use the "login" namespace for those "captcha" related stuff (that could be a workaround, manually edit each "recaptcha' settings, and set their namespace to "login").

So closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by beau-gosse** [comment]
Confirmed. Setting `login` as namespace took care of the problem. I'll file this in Login.
