### ISSUE TITLE
Warn users before executing "log out all users"

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12364]
When a Linux server admin is going to shutdown the server, it is expected that a warning be sent to all users several minutes before the shutdown. It would be nice if a popup warning was given to any users logged in to the mgr context with a brief delay before the "Logout All Users" function was executed.

The delay could even be a System Setting.

 core/model/modx/processors/security/flush.class.php

**Comment by inreti** [comment]
Hey @sottwell, we discussed this in a more general approach at the CCC in cologne (esp. @rtripault and me :-). During our brainstorming for an (semi)automated updater it turned out, that a user messaging system is needed. Summaries of the CCC will be posted later this week...

**Comment by Alroniks** [comment]
I am wondering about implementing this feature. In common case, we have to have a special script that will ask the server about launched logout for all users. A solution may be using web sockets to send push to all logged in users but I am not sure about the support of this feature by browsers.

**Comment by OptimusCrime** [comment]
I am pretty sure implementing something like this is pretty difficult, which is why it is implemented the way it is today (truncate table). Some issues that arise include:

Because PHP can not schedule a task (because it is not a long running process like Java, Python or NodeJS), how are you supposed to empty the table with the session data? You can not in PHP say "empty the table in x minutes". You will have to have the admin user stay on the page until the timer reaches 0, and then run a request.

Another problem is that web sockets also require long running processes to work, something PHP does not handle very well. Additionally, a lot of browsers does not support web sockets today.

If done with ajax requests (which would run every x seconds), there is still a change a user would not get the issue because him or her updated their browser exactly when the request was done.

I would file this as "good idea, but it is not achievable with improved user experience". Or perhaps @sottwell would shed some light on how she imaged this could be implemented?

**Comment by Mark-H** [comment]
Is this needed now that MODX will let you log back in without a refresh if your session was removed? I think that may not have worked properly back in 2015.

**Comment by OptimusCrime** [comment]
I can not see the use for this either.
