### ISSUE TITLE
Manager Times Out When Saving

### ISSUE THREAD

**Issue by alexcua** [modxcms/revolution#12438]
After I click on Save, I get the alert - "Please Wait - Saving....", then the progress bar goes from left to right 2x but does not save. I have to reload the page and then paste back my edits. If I don't save within a minute, it times out again.

I've tried rebooting. Used Firefox and Safari. Got the same behavior. 

Running 2.3.3 in ModxCloud.

**Comment by alexcua** [comment]
This seems to occur only when editing Templates. So far, I have not experienced any while editing chunks even if I let the computer sit for a few minutes, I can still save. So strange.

**Comment by pixelchutes** [comment]
Sounds like a localized issue. I wonder if `mod_security` could be at play here? Are you on Apache?

What happens when saving a Template without any code in it (as a test), for example the words: "This is a test" -- do you see the same delay? Also, have you checked the relevant error logs (PHP, Apache, etc) for any indication of what might be happening?

**Comment by alexcua** [comment]
Im using this on modx cloud. Will keep testing on other machines.

Alexander Cua
This message was sent from my mobile device.

**Comment by alexcua** [comment]
I believe this issue happens when there is a network latency. I have not experienced the issue for the past 2 days.
