### ISSUE TITLE
Remove "New XXX" (create XXX) from the content submenu

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#12517]
I see a lot of clutter in the content submenu. I can't even imagine a use case where creating an element outside the hierarchy would make sense.

![screen shot 2015-07-16 at 10 46 49](https://cloud.githubusercontent.com/assets/667315/8742254/b023c4fa-2c63-11e5-9212-e4505587a8bf.png)

Can anyone come up with a good reason not to remove them permanently from the menu?

**Comment by OptimusCrime** [comment]
What? Where did you get all these menu items from? I only have the first one you scratch out `New Resource`. The rest is not present here. Checked in 2.3.3.

**Comment by fourroses666** [comment]
indeed not present in newest version :o

**Comment by sottwell** [comment]
One of the first things I do for any new installation is to re-install the full resource Search feature, then re-arrange the menu items so that "preview site" is first, "search" is second, "resource groups" is third.

**Comment by fourroses666** [comment]
indeed should be standard that arrangement. and somewhere a directly available quick one click clear cache button without popup I wouldn't mind aswell.

**Comment by sottwell** [comment]
Well, I can't say that I mind that popup. More than once it's alerted me to problems that needed attending to.

**Comment by fourroses666** [comment]
The normal clear cache button will still exsist but just an add-on button for fast clear cache without popup. (Just one example, I use cssSweet and every time I change some css in the chunk I have to clear cache, thats 3!! clicks.)

**Comment by sottwell** [comment]
Well, I use a modified version of CSSSweet that works on resources instead, and uses the OnDocFormSave event, runs getResources internally to grab the content of all the .css -type resources and takes it from there. No chunks, no clearing the cache.

**Comment by sottwell** [comment]
That's why I was agitating to have that "syncsite" checkbox configurable, so it can be turned off for all resources (in my context) for when I'm saving the .css resources.

**Comment by fourroses666** [comment]
Yes I wrote your cookbook post on the modified one. I need to dig into that. 
But I still would like to directly clear cache, at least not in the dropdown.

**Comment by pepebe** [comment]
@sottwell your sort order totally makes sense. I also hate how the package manager get shuffled arround. I don't think I have tow installations where it is in the same place.

Regarding sort order: I would like to have a static block of standard items on top of the submenu and then a separator showing new stuff moved there by plugins. This would make it easier to discern core function from plugins and extensions.

@OptimusCrime and @fourroses666  I'm running 2.3.3 too and I have never bothered to fiddle around with the main menu items. Could be a legacy thing that doesn't show up on new installs. I'll check this later.

Apart from this: Even new resources doesn't make sense for me. Let's send it into retirement...

Anyone else not seeing those items?

**Comment by OptimusCrime** [comment]
I can agree to this:

1. Remove `New Resource`
2. Move `Preview` to the top
3. Move `Search` under `Preview`

**Comment by sottwell** [comment]
The business about the "Extras" menu items came up a few versions ago, got fixed, then regressed. It's a bug that really would be nice to have fixed once and for all.

**Comment by sottwell** [comment]
Well, the "Search" item has to be reinstated to the default installation. The functionality is still there, it's just not part of the default menu any more.

**Comment by pepebe** [comment]
I guess that except "new resource" most menu items that keep nagging me have already been removed. Thats good news!

I just noticed that I also still have search in my content submenu. If anyone is missing it, this might be helpful:

![screen shot 2015-07-17 at 12 39 48](https://cloud.githubusercontent.com/assets/667315/8745521/064413fe-2c81-11e5-8056-9c6c89f69d73.png)

**Comment by sottwell** [comment]
That's because that site is an upgraded site. The "Action" value has to be 'search' for 2.3.x new installations.

**Comment by OptimusCrime** [comment]
Yeah, I am pretty sure this issue is a little wrong. You could do a clean install from 2.3.5 and see if you'd like to change anything in the menu there. The image posted does not reflect how the resource menu looks today.

**Comment by sottwell** [comment]
![screen shot 2015-07-17 at 2 06 18 pm](https://cloud.githubusercontent.com/assets/1073780/8745935/165ca60a-2c8d-11e5-8575-0cf62f21f393.png)

**Comment by pepebe** [comment]
Thank you for shedding some light on this. I've removed all legacy items and updated the search action. This look much cleaner now!

**Comment by pepebe** [comment]
As it turns out that this problem has already been solved in MODX 2.3.+, I guess we can consider this case as closed. 

Thank you!

**Comment by rthrash** [comment]
I do like Susan's suggested order, so there's still room for an improvement here I think. Needs to be handled on upgrades as well as on new installs.

**Comment by OptimusCrime** [comment]
Perhaps worth opening a new issue and clean write everything from scratch?

**Comment by rainbowtiger** [comment]
The main thing here for me is, **please stop moving menu items around after upgrading!** This is the one thing the prevents me being able to hand off MODX upgrades (using the UpgradeMODX plugin) to my clients, because I know I'll have to go in and set up the menus all over again each time. Can we please get this into the queue somewhere??

**Comment by OptimusCrime** [comment]
@rainbowtiger that is not really the issue discussed here. If this is indeed a problem (I don't know), please open a new ticket.

I'm in favor of closing this + potentially also opening a new issue about the reworked order and structure.

@rthrash ?

**Comment by jaygilmore** [comment]
@rainbowtiger what do you mean by "…get this into a queue somewhere??" I understand the issue of moving the furniture around with every release, it makes it hard for users who are not frequently in the UI to be able to use the Manager with confidence. Frankly, UI changes should be considered breaking changes at some level and perhaps should use semver.

**Comment by rainbowtiger** [comment]
@OptimusCrime, What I'm saying IS related, because right now people can set up the menus exactly as described above, but after the next upgrade everything will get shuffled around again. And, although the order proposed above makes sense to me, it still won't suit everyone, and we're back in the same boat of not supporting people's choice of menu order from upgrade to upgrade.

@jaygilmore, I don't see how what I'm talking about is a breaking change. Wouldn't it just be a matter of having the installer not reset the parent and menuindex on menu items if they are already set? By "get it into the queue" I meant assign to to a version number. This has been discussed before, although I did a search and can't find the thread here.

**Comment by sottwell** [comment]
Yeah, it did always annoy me no end to have to go re-arrange the menus after every upgrade.

**Comment by jaygilmore** [comment]
@rainbowtiger I wasn't implying what you were saying was a BC. I was talking about MODX contributors making changes to the Manager interface that would alter the user experience creating frustration of the UI not being the same on a patch upgrade. Relocating the radio buttons every time you took your car in for service would suck.

**Comment by rainbowtiger** [comment]
Ah, I see. Good analogy!

**Comment by rtripault** [comment]
FWIW, since Revo 2.4 you could define the "containers" to use to build your top navigation content, using `main_nav_parent` (for the left part of the top bar) & `user_nav_parent` (for the right part of the top bar) settings ("core > back-end & manager" area).

You would need to create 2 new "containers" in `?a=system/action` & duplicate the records.
The drawback being you can't use twice the same lexicon key in your menus, since that's the database primary key (don't know what drove to this design), so you would need to ship your own lexicons (according you need i18n).

Your custom menus would survive any Revo upgrade.

Hope that helps

**Comment by Mark-H** [comment]
Closing this issue as resolved. As there was a lot of chat, feel free to open a new issue (after searching for existing ones, of course) for things that are still relevant today.
