### ISSUE TITLE
Modx can save only 1000 lines of resource/file

### ISSUE THREAD

**Issue by matimoto87** [modxcms/revolution#12522]
Hi!

Modx can save only 1000 lines of code. If you are trying to save file/resource with above than 1000 line, your file/resource would be cleared with 0B size.

**Comment by markwillis82** [comment]
Hi @matimoto87,

* Could you provide a test example of this?
* Are you creating a resource with the content field being more than 1000 lines?
* Is every line blank? or specific content on each?

Also which version of MODX are you running?

**Comment by matimoto87** [comment]
F.ex. I've uploaded a camera.js file that has 2274 lines. Then I've tried to modify content of this file. After save, modx informed me that the save is completed but in fact, this file is empty now. Modx cleaned all content of it. Please, try it.

I had the same issue with a template. My HTML file had 1455 lines of code and I could save it. The same situation - Modx information : Save success, but the template was empty.

**Comment by markwillis82** [comment]
This could be a local set-up issue rather than MODX itself. The template content column is MEDIUMTEXT which is roughly 16,777,215 characters.

But to achieve that the mysql max_allowed_packet has to be increased. By default this is about 1MB - which is why you are seeing the truncation of the content.

Are you able to try raising this limit and see if the length of text is increased when saving through the manager?

**Comment by matimoto87** [comment]
I will ask my hosting provider. But my camera.js file have 64KB when the default max_allowed_packet have 1MB limit. Does this would have an impact?

**Comment by markwillis82** [comment]
I can create a template on my local development MODX with > 10k lines and am not seeing an issue, it may be your hosting provider has reduced this setting from the default. What version of MODX are you running?

**Comment by matimoto87** [comment]
I will ask him.

MODX Revolution 2.3.5-pl (sdk)

**Comment by matimoto87** [comment]
Hi. I asked my hosting provider about this size and this variable is set for 16M and we can't change it.

**Comment by wshawn** [comment]
Is the OP using TinyMCE or some other editor?  They will occasionally "clean: inserts like this, which is why I refuse them on my sites.  

MODX typically will not touch anything described herein, regardless of length. It doesn't care what you put in there.

16 Megs is drastically low for modern hosting, but sufficient for the OP's needs I would assume. MODX requirements indicate 24 MBs (https://rtfm.modx.com/revolution/2.x/getting-started/server-requirements).

I run 256 MB minimum and some sites have as much as 1G.

I am pretty sure MODX is not the issue.

Here is the entire Bootstrap.css AND the Bootstrap.theme.css set up as a single page (which is over 7300 lines)

http://www.shawnwilkerson.com/bootstrap.css

**Comment by matimoto87** [comment]
Yes, you have right, so we can close this thread recognising it as solved.

**Comment by OptimusCrime** [comment]
I guess we can close this then?

@modxbot close
