### ISSUE TITLE
Improving cache generation/resource save for large sites

### ISSUE THREAD

**Issue by markwillis82** [modxcms/revolution#12520]
I've been spending some time improving the save time of resources within the manager when having 100k + resources, and have tracked the problem down to 2 items. Both related to this file: https://github.com/modxcms/revolution/blob/master/core/model/modx/mysql/modcontext.class.php

The first is the JOIN for `modContextResource` and second being no index that can be used. From my findings I cannot find anywhere that the `modContextResource` table is actually populated (I've got multiple single and multi context sites) but cannot get any new rows added to this table.

I have refactored these functions to be a lot quicker (down from 16 seconds to 1 second on my local machine for 250,000 resources) but want to be sure it won't break anything by removing this table from the query.

Is this some old/dated code that can be removed?

There is a great comment here:
https://github.com/modxcms/revolution/blob/master/core/model/modx/modcontextresource.class.php#L12
`@todo Work this relationship into use in the manager and the logic of each` dating back to 2011

**Comment by OptimusCrime** [comment]
Wow, this is amazing. If this works, dude.

**Comment by OptimusCrime** [comment]
I did some digging myself and found the following line in the [changelog](https://github.com/modxcms/revolution/blob/9df6a1b6529ddfd14183a814366caa910653ba71/core/docs/changelog.txt#L2880):

> modCacheManager->generateContext(): Added support for Resources to be generated in multiple contexts via modContextResource.

From version 2.0.0-beta-1.

Other results are the one you linked and mentioned once in a the method for returning resources, that I can't decode or figure out.

**Comment by markwillis82** [comment]
I should add... the only references to this object are:
```
./core/docs/changelog.txt
./core/model/modx/metadata.mysql.php
./core/model/modx/metadata.sqlsrv.php
./core/model/modx/modcontextresource.class.php
./core/model/modx/modrequest.class.php
./core/model/modx/mysql/modcontext.class.php
./core/model/modx/mysql/modcontext.map.inc.php
./core/model/modx/mysql/modcontextresource.class.php
./core/model/modx/mysql/modcontextresource.map.inc.php
./core/model/modx/mysql/modresource.map.inc.php
./core/model/modx/sqlsrv/modcontext.class.php
./core/model/modx/sqlsrv/modcontext.map.inc.php
./core/model/modx/sqlsrv/modcontextresource.class.php
./core/model/modx/sqlsrv/modcontextresource.map.inc.php
./core/model/modx/sqlsrv/modresource.map.inc.php
./core/model/schema/modx.mysql.schema.xml
./core/model/schema/modx.sqlsrv.schema.xml
```

Any references tend to be getObject - nothing actually creates data in the table

**Comment by OptimusCrime** [comment]
You might actually have found the ghost in the machine!

**Comment by opengeek** [comment]
I've used this since we created Revo to add Resources to multiple "secondary" contexts by simply creating a multi-select TV of Contexts and attaching a plugin that manages the records. The intention was that this feature be added to the core manager UI, but it seems to have been forsaken.

Perhaps we could make it an optional relationship that has to be explicitly enabled?

**Comment by markwillis82** [comment]
How are you adding records to the table? Manually? Are you able to explain what/how it works? Adding a system setting would be an ideal solution

**Comment by opengeek** [comment]
```php
$contextResource = $modx->newObject('modContextResource', array('context_key' => $contextKey, 'resource' => $resourceId));
$contextResource->save();
```

We could add a system setting for sure, defaulting to disabled, and investigate if there is a way to improve the join with an optimized index.

**Comment by OptimusCrime** [comment]
I still don't understand how this is used. All Resources have the contextKey stored in the `modResource` object, and in the same table without any join. So what does this add? Allow for a resource to be in multiple contexts?

**Comment by opengeek** [comment]
Yes

**Comment by OptimusCrime** [comment]
This is imo a critical issue that should be resolved

**Comment by wuuti** [comment]
#modxbughunt currently working on this. Can confirm, that the actual behaviour results in long query times if you have a lot (10K+) resources in a context. Furthermore the query is executed once for every context, so if you have 10 contexts and a huge overall amount of resources, the manager UI ends up with waiting for the queries to return (in large installations this can be long enough to get into a timeout!).

**Comment by opengeek** [comment]
I'm pretty sure we addressed this already and optimized the cache generation. We added settings like cache_alias_map which you can disable to reduce the generation time for large sites. It should be disabled for large sites, in fact.

**Comment by wuuti** [comment]
### Analysis ###
The following query is executed (on resource save 4x, on system setting change 2x per context):
```
SELECT 
    `r`.`id`, `r`.`parent`, `r`.`uri` 
FROM
    `modx_site_content` `r` FORCE INDEX (CACHE_REFRESH_IDX)
        LEFT JOIN
    `modx_context_resource` `cr` ON `cr`.`context_key` = 'context_key'
        AND `r`.`id` = `cr`.`resource` 
WHERE
    `r`.`id` != `r`.`parent`
        AND 
        (`r`.`context_key` = 'context_key'
        OR `cr`.`context_key` IS NOT NULL 
)
        AND `r`.`deleted` = 0
GROUP BY `r`.`parent` , `r`.`menuindex` , `r`.`id`
```

* one expensive part is the _group by_ statement: despite the fact, that it uses a field (menuindex) which is not returned by the select at all, the same results can be done by a SELECT DISTINCT
* querying for and returning the URI is not necessary if cache_alias_map is false (which is recommended on large installations!)
* the join with the modx_context_resource is not necessary because the (weird) functionality for that was never implemented, so we can drop the join. IMHO completely, but that can also be done transparently with the previously mentioned system setting 'use_contextresource_table` activated by default to not change the behaviour of existing systems. We should add to the cache_alias_map description that in case of large installations also the new setting should be deactivated. 
* the comparison  `r.id != r.parent` is totally useless, isn't it? there will never by a resource which is also its own parent...
* the index being forced is not necessary if you do not use the group by statement. 

So IMHO we could run the same with the query (cache_alias_map=false, use_contextresource_table=false) , which is about factor 50 better. 
```
SELECT DISTINCT `r`.`id`, `r`.`parent`
FROM
    `modx_site_content` `r`  
WHERE
        `r`.`context_key` = 'context_key' AND `r`.`deleted` = 0
```
I am going to make a PR for that, imho critical legacy ... let's call it ... accidentially half-introduced behaviour. 

We can also discuss if we still need to disable the cache_alias_map if the underlying queries are fast even on large sites from now on... IMHO the recommendation to turn this off becomes obsolete if we optimize the queries here.

**Comment by opengeek** [comment]
cache_alias_map is not just about performance, it's also about cache file size. The context cache files become insanely large if this is enabled on large sites, so yes, it should still be disabled on large sites.

**Comment by opengeek** [comment]
Be sure this is targeting at 2.6, not 2.5. This is introducing new settings and behavior.

**Comment by wuuti** [comment]
@opengeek if we set the default settings value to not change anything, it won't change behaviour unless you configure it. Isn't it then a fix for a (performance) bug?

**Comment by opengeek** [comment]
When introducing settings, we generally require a minor release bump as those settings are not available in previous releases of that minor branch and it makes it difficult to document properly. But I am willing to consider arguments to the contrary.

**Comment by OptimusCrime** [comment]
#13360 introduced a new setting which is capable of disabling the additional lookup. I want to see this setting turned on by default in a major release, but that is outside the scope of this issue.

@modxbot close
