### ISSUE TITLE
OnMODXInit is not working for static plugins

### ISSUE THREAD

**Issue by ambienthack** [modxcms/revolution#12574]
I mean plugins that are stored as separate files. If checkbox "static" is unchecked plugin works as expected.

Seems like MODx fails to create cache item for the plugin properly. A file that sits inside /core/cache/includes/elements/modplugin/. It is created but without actual plugin code.

**Comment by ambienthack** [comment]
![screenshot](https://sc-cdn.scaleengine.net/i/549d761655dd6f4a85ac0b814f7e0a36.png)

**Comment by bezumkin** [comment]
I will try to fix it.

**Comment by bezumkin** [comment]
I can`t confirm it. On MODX 2.6.1 static plugin works as expected.

<img width="1055" alt="2018-02-09 14 13 50" src="https://user-images.githubusercontent.com/1257284/36029456-8ffd0230-0da3-11e8-9949-b86e20eff5f3.png">
<img width="582" alt="2018-02-09 14 13 57" src="https://user-images.githubusercontent.com/1257284/36029457-91c2aa7a-0da3-11e8-9b0c-e968c653844c.png">
<img width="951" alt="2018-02-09 14 14 16" src="https://user-images.githubusercontent.com/1257284/36029461-94394f20-0da3-11e8-9958-6c7344a5ec79.png">

Maybe your has your problem because of empty media source (on your screenshot).

**Comment by gpsietzema** [comment]
@modxbot close
