### ISSUE TITLE
No "lcfirst" output filter

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12708]
There is "ucfirst" output filter that mirrors PHP function with the same name, but there isn't corresponding "lcfirst" filter to "decapitalize" output. Of course it can be easily made by hand, yet it should be bundled by default.

**Comment by sottwell** [comment]
Wouldn't the 'lcase' modifier take care of it?

**Comment by whitebyte** [comment]
No. It make every word in the output lowercased, while `lcfirst` modifies only the first word.
The solution is actually trivial:
```php
<?php
return mb_strtolower(mb_substr($input, 0, 1)) . mb_substr($input, 1);
```
But I still think it shuld be include for symmetry with `ucfirst`

**Comment by sottwell** [comment]
Well, for what it's worth, it's always been my opinion that modifiers that only wrap ordinary PHP functions shouldn't be in the core. The only ones that should be in the core should be those that use the MODX API, such as userinfo.

The rest of them could be a snippet with functions in a gist or something. Just not in the core.

**Comment by whitebyte** [comment]
I don't clearly understand by what criteria filtres are added. Right now it looks like a "kitchen sink" approach. If so `lcfirst` is worse nothing than the others. If not, lots of existing filters should be removed (I secretly love this idea)

**Comment by inreti** [comment]
I don't like the idea to _not_ have filters like that in the core. The output filters are one of the outstanding yet simple to use features of MODX. And I don't want to add a snippet whenever I just want to quickly use one - neither by a gist or by writing 'trivial' wrapper snippets myself (even a trivial filter needs some time for testing). 
Having more or keeping the existing filters does not add complexity to the core, because they inherently provide independent code (like an integrated microservice). So I don't see any code maintenance or dependency arguments for removing them or not adding more filters. But I do see a lot of reasons to have powerful but simple to use output filters _out of the box_, which make it possible to use functions without having to deal with PHP code - a valuable reason if we want to attract more people to MODX at all...

**Comment by OptimusCrime** [comment]
I really don't see the problem of adding this yourself. If this should be added, there are *many* other functions that should be added too.

**Comment by whitebyte** [comment]
@OptimusCrime it's not a big deal to write filters by hand. But their initial set should be consistent, it should follw some general plan. Right now it's just a pile of randomly picked wrappers. `lcfirst` is just a minor issue. 

For example, if there is `urlencode` filter thet mirrors PHP urlencode, where is `rawurlencode` equivalent? 

Another example - `isloggedin` and `isnotloggedin` filters. Do we really need a separate values for `true` of `false` of the same function? Shouldn't we just use `[[+modx.user.id:isloggedin:is=true]]` and `[[+modx.user.id:isloggedin:is=false]]` or `[[+modx.user.id:isloggedin:isnot=true]]`?

There are other examples.

**Comment by Mark-H** [comment]
The use case for ucfirst it to make the first character of a word a capital, for example to use at the start of a sentence. `[[+name:ucfirst]], thank you for your order.` 

This is the first time I've heard of `lcfirst`.. what's the use case?

**Comment by whitebyte** [comment]
```
<h1>[[*pagetitle]] [[*longtitle:lcfirst]]</h1>
```

**Comment by sottwell** [comment]
If we put in every filter that everyone wanted we'd end up with an impossibly bloated core. I still say what I said more than a year ago, and agree with whitebyte, the MODX core should not be used for simply wrapping basic PHP functions.

**Comment by OptimusCrime** [comment]
In favor of turning this request down.

**Comment by Jako** [comment]
It is very easy to create a snippet based output filter for this. Maybe a collection of those filter codes. But I prefer to use a snippet if the chain of filters extend 3.
