### ISSUE TITLE
Lost Deactivated Plugin Indicator

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12710]
### Summary
Plugins in the Element Tree no longer indicate their activation status

### Step to reproduce
Activate and deactivate a plugin and look at it in the Tree.

### Observed behavior
There is no change in the listing.

### Expected behavior
The plugin should change text color to a lighter gray when deactivated.

### Environment
Revo 2.4.2

**Comment by inreti** [comment]
Seems that the `element-node-disabled` class does not apply any more...

**Comment by pixelchutes** [comment]
Does anyone recall the last version this whether correctly, for reference?

**Comment by sottwell** [comment]
2.4.1

**Comment by pixelchutes** [comment]
Something due to #12699 perhaps?

**Comment by inreti** [comment]
@pixelchutes: checked that, indeed it was a change from me made for #12699 in _colors-and-vars.scss:
`$unpublished: lighten($treeText, 10%) !important;`
to
`$unpublished: $treeText;`
That's odd somehow, because unpublished shouldn't have anything to do with activated/deactivated. 
But the there is also a `$disabled: $unpublished` in the definitions - which pushed the `!important` towards our deactivated node. That's the problem with messing up css styles down an extjs tree and using the same definition for different purposes... 
I will make a correction PR for that - hopefully without such a sideeffect.
