### ISSUE TITLE
runSnippet messed up parameters

### ISSUE THREAD

**Issue by vasyahuyasa** [modxcms/revolution#12761]
I have two snippets, first one is qsPrint:
```
<?php
    return print_r($scriptProperties, 1);
```

And second one is like this:
```
$params = [
    'data' => [
        'key' => 'qweqwe',
        'value' => '2342234',
        ]
];

$output = $modx->runSnippet('qsPrint', $params);
return $output;
```
I were expected to get in $output 2 dimension array but get in output this:
```
Array ( 
    [data] => 2342234 
)
```

**Comment by christianseel** [comment]
I'd say this is "by design" because $scriptProperties should always be a simple associative (non-multidimensional) array to be parsed into placeholders etc.

Looking at the MODX parser at https://github.com/modxcms/revolution/blob/e1d0f054d1ac5431e93008aaca517f93a39667ee/core/model/modx/modparser.class.php#L284 you can see that whenever a key `value` is found that value replaces the sub-array.

**Maybe** the condition in L301 could be modified to
```
if (is_array($property) && array_key_exists('value', $property) && count($property) === 1) {
```
…so making sure that the array key `value` is the only value in the sub-array. That would solve your reported issue in my testing. But it might raise other issues. I'm not sure and haven't done any further testing here.

**Comment by Jako** [comment]
If you want multiple dimensional arrays in one property, you have to work with json_encode/json_decode for the reason @christianseel already mentioned. Snippet calls have to be callable in a resource/content/template and you can't use php array values there.
