### ISSUE TITLE
Duplicating form customisation sets (security/forms/set/duplicate) causes SQL error on name check

### ISSUE THREAD

**Issue by faitno** [modxcms/revolution#12886]
I'm have issue with copy Form Settings:
action:security/forms/set/duplicate
With 500 error, explain:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22] [1054] Unknown column 'modFormCustomizationSet.name' in 'where clause'' in /core/xpdo/xpdo.class.php:1037
Stack trace:
#0 /core/xpdo/xpdo.class.php(1037): PDOStatement->execute()
#1 /core/model/modx/modprocessor.class.php(1057): xPDO->getCount()
#2 /core/model/modx/modprocessor.class.php(974): modObjectDuplicateProcessor->alreadyExists()
#3 /core/model/modx/modprocessor.class.php(173): modObjectDuplicateProcessor->process()
#4 /core/model/modx/modx.class.php(1703): modProcessor->run()
#5 /core/model/modx/modconnectorresponse.class.php(131): modX->runProcessor()
#6 /core/model/modx/modconnectorrequest.class.php(82): modConnectorResponse->outputContent()
#7 /core/model/modx/modconnectorrequest.class.php(69): modConnectorRequest->prepareResponse()
#8 /connectors/index.php(71): modConnectorRequest->handleRequest()
#9 {main}
```

I'm use HHVM 

```
HipHop VM 3.11.0 (rel)
Compiler: tags/HHVM-3.11.0-0-g3dd564a8cde23e3205a29720d3435c771274085e
Repo schema: 52047bdda550f21c2ec2fcc295e0e6d02407be51
```

ans latest MODX 

```
2.5.0-dev
```

**Comment by whitebyte** [comment]
Just curious, is HHVM officially supported? AFAIK MODx requires PHP, and PHP !== HHVM, so is it an issue?

**Comment by OptimusCrime** [comment]
@whitebyte Nope, not officially (as far as I know), but I think full support for it is a goal.

**Comment by Omeryl** [comment]
If I recall doesn't hhvm consider things that don't work as bugs on their end? Besides a few things.

**Comment by OptimusCrime** [comment]
True, but could this be a notice or warning in PHP that is treated as a fatal error in hhvm?

Worth checking out imo.

**Comment by guyinpv** [comment]
I've been digging in to this. I am not intimately familiar with the MODX core so forgive me as I explain my findings, hopefully someone can add to the discussion and figure out the correct update needed in the core, as it probably WILL be a core update deep in the heart of MODX!

1) This is probably nothing to do with HHVM, except in that HHVM is being much more hard about showing the error, while the rest of us on Apache or whatever, are not shown the error and it appears to us nothing is happening.

2) The error is exactly as described, it's a simple MySQL query error `modFormCustomizationSet.name` doesn't exist. `modFormCustomizationSet` is an alias, it's actually the table `fc_sets`. And indeed, there is no `name` column in this table! Not in the latest 2.5.5 and not in OP's 2.5.0.

3) Poking through the core code as much as I can, with help from Markh, it would seem that the core essentially expects all tables which use this duplicating feature, to have a name column.

The `xpdo.class.php` file contains the function `getCount()`, this is where the error is triggered which causes HHVM to halt, but not for the rest of us where it is ignored.

The actual query that is attempting to run is something like this:
```
SELECT COUNT(DISTINCT `modFormCustomizationSet`.`id`) FROM `fc_sets` AS `modFormCustomizationSet` WHERE `modFormCustomizationSet`.`name` = ?
```
Notice the question mark at the end for a named parameter? Well there is no named parameter, as there is no `name` column. Running this query produces the exact MySQL error code 1054 as in the OP.

So where is this query being assembled? And where can the fix be injected? This is where my research gets cloudy.

In `core/model/modx/modprocess.class.php` is the function `process()`. This function is making the assumption about there being a name.
```
public function process() {
.
.
.
    $name = $this->getNewName();
    $this->setNewName($name);
    if ($this->alreadyExists($name)) {
        $this->addFieldError($this->nameField,$this->modx->lexicon($this->objectType.'_err_ae',array('name' => $name)));
        }
.
.
.
}
```

The calls to `getNewName()` and `setNewName()` and `alreadyExists()` all depend on having `name` text. It is the `alreadyExists()` function that calls the `getCount()` function which causes this error to trigger.

If I go in the `getNewName()` function:
```
public function getNewName() {

// THIS WILL RETURN AN EMPTY STRING        
$name = $this->getProperty($this->nameField);

// DUE TO THE EMPTY STRING, IT RETURNS 'duplicate of'
$newName = !empty($name) ? $name : $this->modx->lexicon('duplicate_of',array('name' => $this->object->get($this->nameField)));
    return $newName;
}
```

Even though the above function will return "duplicate of", it doesn't matter anyway, since there is no `name` column.

The table `fc_sets` does not utilize a `name` column, so somewhere in the logic of these functions it needs to assemble the query without the use of the `name` column. The assumption seems to be that there will always be a `name` column and it is testing for duplicates and generating a new name.

I just don't know if the extra test regarding `name` should be in the `getNewName()` function or `setNewName()` or `alreadyExists()` or even `getCount()` or the master `process()` function which calls the rest in turn.
I also don't know if form control option sets are the only objects that don't utilize a `name`. Maybe there are others? Some kind of test is needed to check for a "nameless" object.

Hope that helps!

**Comment by alroniks** [comment]
Do we still support HHVM? After PHP7 with a huge performance improvement, it does not make sense support it. Could it be closed? @opengeek @Mark-H @OptimusCrime

**Comment by Mark-H** [comment]
I think this is a bug worth solving even if we don't officially support HHVM, as Zack's research shows a logic flaw/oversight in the duplicate check.

**Comment by Jako** [comment]
I reopen this to check the name column requirement next time.

**Comment by OptimusCrime** [comment]
@Alroniks I agree with @Mark-H. I do not think we should spend time supporting HHVM, but we should fix this issue regardless.

**Comment by Mark-H** [comment]
I'm no longer able of reproducing this in 3.0.0-rc1 on php 8.0, closing.

If it does pop up again, adding the following to core/src/Revolution/Processors/Security/Forms/Set/Duplicate.php should do the trick to avoid this check:

```
    public function alreadyExists($name)
    {
        return false;
    }
```

**Comment by Omeryl** [comment]
This was never an issue in PHP, but HHVM.

**Comment by Mark-H** [comment]
PHP 8 takes on a lot of the strictness from HHVM and by default invalid queries like this also cause a PDOException like the one reported. However we've tweaked that in xPDO so instead it would typically log a warning for invalid queries like this one. 

I've not been able to get anything like this to log, though, so unless new steps to reproduce are reported this issue is closed. If it's exclusive to HHVM, that also is not supported.

**Comment by Omeryl** [comment]
Yeah but the issue was left open in case someone wanted to provide the needed changes, but now it's just being hidden. It doesn't seem bad to me to leave it open if someone wanted to PR it..
