### ISSUE TITLE
Enhacement. New content type: Atom (application/atom+xml)

### ISSUE THREAD

**Issue by mishantrop** [modxcms/revolution#12892]
Please, add new content type. Atom feed must be server up with a mime-type of 'application/atom+xml'.

**Comment by OptimusCrime** [comment]
You can easily add new content types as described in [this tutorial](https://rtfm.modx.com/revolution/2.x/making-sites-with-modx/structuring-your-site/resources/content-types).

I don't really see the need of adding this content type in the MODX core.

Closing this due to lack of popularity. Feel free to reopen or comment if you feel otherwise, have any comments or have further information.

@modxbot close
