### ISSUE TITLE
2.5.0rc2 access policy

### ISSUE THREAD

**Issue by arimanr** [modxcms/revolution#12953]
### Summary

Не сохраняются политик доступа. После простановки чекбоксов и обновления страницы, все настройки исчезают, а политики достeпа полностью сбрасываются.

Not saved access policies. After prostanovki checkboxes and refresh the page, the settings disappear and the access policy is fully discharged.
### Environment

modx 2.5.0rc2 Apache php5.4   browser - YandexBrowser (Chromium)

**Comment by Alroniks** [comment]
After picking up checkboxes you should push "Save" button for apply selected permission into access policy. Otherwise, they won't be saved.

Thank you for your impact @arimanr 
I've checked in 2.5.7 and all works as expected, so I am closing this issue.
Feel free to reopen if you'll be faced it again.
