### ISSUE TITLE
Smarty Autoload function halts and causes error on install

### ISSUE THREAD

**Issue by mrhaw** [modxcms/revolution#12978]
### Summary
Smarty Autoload function halts and causes error on install. + Overwrites your files.

### Step to reproduce
This forum post is doing a good job:  
https://forums.modx.com/thread/99520/revo-2-5-installation-issue-with-method-pear-autoloader-call-in-smarty-class-semisolved

### Observed behavior
It halts installation after setting your core path and give you
PEAR_Autoloader Error message:
`PHP Fatal error:  Method PEAR_Autoloader::__call() must take exactly 2 arguments in /usr/local/pear/PEAR/Autoloader.php on line 211`

### Expected behavior
You should be able to go through the installation process.

### Environment
Me: Win / XAMPP 
PHP Version 5.4.7
5.5.27 - MySQL Community Server

The forum post describes a linux installation:
https://forums.modx.com/thread/99520/revo-2-5-installation-issue-with-method-pear-autoloader-call-in-smarty-class-semisolved

**Comment by OptimusCrime** [comment]
Does anyone with XAMPP experience the same problems? I do not have access to such a environment, so I am unable to test this.

**Comment by mrhaw** [comment]
I am totally stuck on understanding this issue.

"PEAR_Autoloader does not work in PHP 5, it is deprecated and replaced by the PEAR_Delegator package."
http://pear.php.net/bugs/bug.php?id=4426&edit=3

**Comment by Mark-H** [comment]
Do you have a really old version of pear installed or something?

**Comment by mrhaw** [comment]
Thanks Mark. Yes, I am running microsoft php drivers for SQL Server and had to match a xampp for the correct PHP egg... long story short! That was the issue! :)

**Comment by it-scripter** [comment]
Today I had this problem in the wildlife: the upgrade of a website, hosted at the german provider mittwald, let me came in trouble. I haven't the permission to change the php.ini to let the PEAR-path out. 
The problem came up at the upgrade to 2.5.2 - even at the upgrade with the browser so I ran the upgrade with the cli process. The frontend came up, but the manager of course not. 
My solution is now to clean up the path setting inside the core/config/config.inc.php - I know this isn't a save place.

May be it is helpful for others coming along to this page with the same error.

```
/* clean up the include path to fix the PEAR-Problem with the smarty autoloader - TB20161119 */
$indexPathNewArray = [];
foreach (explode(':',ini_get('include_path')) as $includePath) {
	if (!strpos($includePath, 'PEAR')) {
		$indexPathNewArray[] = $includePath;
	}
}
ini_set('include_path',join(':',$indexPathNewArray));
```

What do you think, is it nessecary to include this into the regular code and how do you prefer this?

Thorsten
