### ISSUE TITLE
getChildIds on big tree

### ISSUE THREAD

**Issue by gelid** [modxcms/revolution#13047]
### Summary
when use getChildIds on big modx tree CPU usage 100% 
tree content more 10k parents and 4 level depth

### Step to reproduce
on big modx tree use getResources or pdoResources and filter by template for example.

### Environment
MODX: 2.4.2-pl
CPU: 2000
RAM: 512
OS:	ubuntu12.04-x86_isp_lite
Apache: 2.2.22
MySql: 5.5.24-0
PHP: 5.3.10-1

**Comment by OptimusCrime** [comment]
Pretty sure this is more or less unsolvable. Because PHP usually spawns a new instance, there is no way to limit the CPU usage. This might be possible if you run a continuous process in nginx or apache, I am not sure.

Once more, because every single one of these resources are created as an instance of `modResource` it will consume a lot of RAM/CPU. I just don't think there is any way to fix what you are experiencing. Either limit the fetch, do it another way or use custom tables for you excessive data.

**Comment by garryn** [comment]
Have you tried turning off alias map caching in the system settings? For large sites like this, we recommend that.

**Comment by OptimusCrime** [comment]
@garryn Can we say this is a "wontfix" as there is no way to get around this problem? It is simply the way it is when dealing with huge sets of resources.

**Comment by OptimusCrime** [comment]
Closing for reasons mentioned above.

@modxbot close
