### ISSUE TITLE
All assigned resource groups are not stored on resource save.

### ISSUE THREAD

**Issue by ByteJamRob** [modxcms/revolution#13140]
I'm finding that not all resource groups assignments are being saved when the resource group tab of the resource edit window is paginated.

I have a site with 190 resource groups. By default, in the Resource Group tab of the resource edit screen they are paginated at a rate of 20 per page. If I check a group, then go to another page, then check a group, then go to another page, the check a group, only the last group gets stored when I save the resource. This is true for both new and existing resources.

There are, of course, two workarounds:
1. Change the paging threshold so that no paging occurs.
2. Save the resource before stepping to the next page of resource groups.

Nevertheless, this is causing some client confusion, so I'm opening this ticket. 

I've tested this on MODX Revolution 2.5.1 running at MODX Cloud.

**Comment by Mark-H** [comment]
190 resource groups 😱

**Comment by Mark-H** [comment]
I don't think there's any paging treshold that is both reasonable and will let you see 190 resource groups, but I'm going to mark this as accepting pull requests in case someone can think of another way to keep the checked resource groups in memory so they can be submitted in one save.

**Comment by pixelchutes** [comment]
@ByteJamRob can you please confirm if this is still an issue after upgrading to MODX 2.5.6? I'm curious if this was inadvertently fixed by #13399

If I understand this correctly, is it possible you were only experiencing the issue above when dealing with protected Weblink, Symlink or Static Resources?

Based on my findings, paging in the Resource Group grid was previously only enabled for these types, but should [no longer](https://github.com/modxcms/revolution/pull/13399/files) [be the case](https://github.com/modxcms/revolution/blob/d76a4197e7ef710872601de590d0dcf48d5cad02/manager/assets/modext/widgets/resource/modx.grid.resource.security.local.js#L13)_

**Comment by ByteJamRob** [comment]
@pixelchutes you are quite correct on all counts! I was indeed experiencing the issue for Static Resources (big document repository with complex permissions model). Upgrading to 2.5.6 fixes the issue in the sense that it removes pagination. All my resource groups are getting displayed at one time. 

I'm OK with closing the issue. I'd already implemented a substantially similar work-around and the client has been satisfied with it.
