### ISSUE TITLE
SEO Tab is not appearing in Resource after installing it via Package Management.

### ISSUE THREAD

**Issue by ravikandel1** [modxcms/revolution#13150]
### Summary
Quick summary what's this issue about.

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by Jako** [comment]
Please follow the (contributing guidelines)[https://github.com/modxcms/revolution/blob/2.x/CONTRIBUTING.md] next time, if you open an issue and fill the issue template instead of creating just a title describing the issue.

I am closing this because it is not a MODX issue but a SEOTab one. Post the issue there: https://github.com/Sterc/SEOTab/issues
