### ISSUE TITLE
flush_sessions_err

### ISSUE THREAD

**Issue by RayEagle** [modxcms/revolution#13222]
### Summary
Quick summary what's this issue about.
When I try "Flush all sessions" the error of "flush_sessions_err" jumps out. How to solve a problem? 

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.
2.5.2, nginx, MariaDB

**Comment by OptimusCrime** [comment]
According to this code: https://github.com/modxcms/revolution/blob/fbf126690f6ce903faeaeb9f1d958211fc2203c9/core/model/modx/processors/security/flush.class.php#L28

The processor will be successful unless the query "TRANCATE TABLE [your session table name here]" fails. Are you sure your database user has sufficient permissions to execute a query like that? Other than that I see no other way you should get the error.

Could you try running the query in a database shell, phpmyadmin, MySQL Workbench or similar? Pretty sure the problem is not MODX related.

**Comment by Mark-H** [comment]
Appears to be a mysql rights issue.
