### ISSUE TITLE
Active password without confirmation

### ISSUE THREAD

**Issue by MrRoco** [modxcms/revolution#13270]
### Summary
On password reset users get an mail which contains their email and an activation link.
We experience that a lot of people just skip the confirmation because the password is above it.
It would be a nice feature if the password would be active on the reset, so it's not necessary to activate it with the link, maybe based on system setting.

### Step to reproduce
User management > user > send password by mail

### Observed behavior
Receiving mail with password, people copy the password without activating it and get confused because the password is not working.

### Expected behavior
Having the password active when it's send to the client.

### Environment
Every modx revolutin install

**Comment by pixelchutes** [comment]
This activation step is very important. Otherwise, there is nothing preventing someone from hijacking another user's account, effectively changing their password by simply entering someone else's email address into the reset form.

That is why you commonly will see reset emails with a link, along with language similar to: 

> If you did not request this, please ignore.

Unfortunately I am closing this request as I believe it would be a big step backwards for User security in MODX. Also, it may very well be possible to create a custom component to achieve this behavior, but I do not recommend this path, especially for the MODX core.
