### ISSUE TITLE
Scroll issue in Modx Revolution with Ubuntu 16.04

### ISSUE THREAD

**Issue by vinodjoshi** [modxcms/revolution#13386]
### Summary
I have installed fresh copy of Modx Revolution 2.5.5 on my Ubuntu Server. After then i have installed Store Locator Components.

After adding more then 15 stores i am not able to scroll down to see further stores.

Please see the Screenshot
**http://prntscr.com/ejhiur**

### Step to reproduce
Its issue with Modx Revolution latest version on Ubuntu

### Environment
MODX version -> 2.5.5, 
apache2 -> 2.4.18
mysql version -> mysql 5.5.17, 
Ubuntu 16.04

**Comment by Jako** [comment]
This is a [StoreLocator](https://github.com/b03tz/StoreLocator) issue and not a MODX issue.

Maybe it is fixed with this commit: https://github.com/brescianicri/StoreLocator/commit/aed47a9f711bffbd9a536553c37985c33f4b4211

The StoreLocator package seems to use quite old code, that was not maintained for more than 5 years.

**Comment by vinodjoshi** [comment]
Hi Jako,
Thanks for your help it has solved my Scroll issue, But could you tell me why its happen in FormSave extra ?

And also i am not able to sorting any coloum from table
**http://prntscr.com/ejwy7y**

How can i solve this ? This also happen in Formsave extra.

**Comment by OptimusCrime** [comment]
@vinodjoshi This is not the place to ask for such help. Either visit the [modx forums](https://forums.modx.com) or join the [modx slack channel](http://www.modx.org).
