### ISSUE TITLE
Forgot Password in Manager allows User/Email enumeration.

### ISSUE THREAD

**Issue by Omeryl** [modxcms/revolution#13408]
### Summary
The forgotten password utility on the manager allows user and email enumeration because it will announce if a user doesn't exist.

### Step to reproduce
1. Head over to /manager/
2. Try any user or email in the forgot password fields. 

### Observed behavior
If it exists it'll say it succeeds. If it fails, it'll say it failed.

### Expected behavior
It should state something like "If the user or email exists, you'll receive an email shortly." instead of disclosing that a user/email did/didn't exist. 

### Environment
Any and all environments.

**Comment by pixelchutes** [comment]
Great point, @Omeryl I think this is a good recommendation for an improved, default behavior.

That said, since these error messages are managed at the Lexicon level, couldn't one choose to update the two individual lexicon keys to serve the same value, vs. differentiating (read: disclosing) as it does today? This currently gives users the control to differentiate if they so choose.

**BEFORE:**
> `login_user_err_nf_email` = User not found with that email or username. Please try again.
> `login_password_reset_act_sent` = Password Reset Activation email sent. Please check your inbox.


**AFTER:**
> `login_user_err_nf_email` = If the user or email exists, you'll receive an email shortly.
> `login_password_reset_act_sent` = If the user or email exists, you'll receive an email shortly.


![same_lexicon](https://cloud.githubusercontent.com/assets/352182/24628612/4dd69666-1874-11e7-901d-b31b2e656fc4.jpg)


![example_ambiguous](https://cloud.githubusercontent.com/assets/352182/24628574/27ef25da-1874-11e7-844b-94ef989c5a1a.jpg)

**Comment by Omeryl** [comment]
@pixelchutes I believe, in this case, the default should be oblivious to the public entirely, an opt-in to insecurity vs an opt-out.

**Comment by pixelchutes** [comment]
Exactly! 👍 Makes sense to me. I think easily accomplished w/ a lexicon change vs. code change, keep flexible if (for some reason) the alternative may be preferred/required.

**Comment by OptimusCrime** [comment]
I think this is fixed with the merged PRs above. Feel free to correct me.

@modxbot close
