### ISSUE TITLE
Failing to download from HTTPS Package provider with old curl version

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#13417]
### Summary
On some server configurations (the most common factor I've found is a low curl version, before 7.37 or so) downloading packages fails from a package provider which uses HTTPS. This has mostly affected the modmore provider in the past, but now that MODX also uses HTTPS by default, it may also pop up here more often.

It seems to be unable to connect, and while a detailed error message isn't provided, my long term suspicion has been that the older versions of curl don't default to the most modern encryption (basically TLS1.1/2 instead of SSL3). As SSLv3 isn't supported on my server (not sure how the MODX provider is configured), the connection fails and the user can't download a package.
 
### Step to reproduce
Get an old environment (e.g. cURL 7.19.7 and OpenSSL 1.0.1) and try to download an extra from modmore or possibly MODX. 

### Observed behavior
Failure to download.

### Expected behavior
Properly download extra

### Environment
Any MODX version (at least since 2.2/3), most importantly PHP compiled with an old version of cURL. 

### Possible solution
Perhaps we can work around the issue by providing the `CURLOPT_SSLVERSION` option with the TLS value in the package provider's download code (modTransportPackage->transferPackage), but if the system attempts to download with file_get_contents/fread, that wont help. 

Another option could be to refactor the transferPackage code to properly fall back to other methods of downloading if it doesn't work. It could try file_get_contents/fread first, if that didn't work, try curl, and if that didn't work, use sockets. Right now it just picks one based on available functions so even if cURL would work, if file_get_contents/fread didn't work, it wont even bother trying and the user can't install their package.

**Comment by pixelchutes** [comment]
Excellent points, @Mark-H. I bet you're right on the money, and soon this will also include a wider drop in support of TLS 1.0, at least as far as PCI compliance is concerned.

This made me think of the PCI Data Security Standard (PCI DSS) version 3.1 [originally mandating](https://blog.pcisecuritystandards.org/migrating-from-ssl-and-early-tls) that:

> All processing and third party entities – including Acquirers, Processors, Gateways and Service Providers must provide a **TLS 1.1 or greater** service offering by June 2016

However, Payment Card Industry Security Standards Council (PCI SSC) ended up extending this date to June 30, 2018 (though they don't recommend waiting.)

I am curious, does MODX currently define minimum required versions for accompanying libraries (like OpenSSL, cURL, etc) anywhere? I like your fallback ideas, especially since it would help some individuals keep moving forward, but at some point _(maybe 2018, maybe sooner, maybe later)_ I wonder if setting a version dependency will become a requirement, in the name of security.

**Comment by Mark-H** [comment]
I've just wrapped up #13419 which implements the fallback. 

I don't think there are minimum versions for curl/openssl, I also wouldn't know what they should be, but I did confirm that with #13419 a customer was able to download a package from modmore which previously did not work. Security wise there's probably more we can do on this topic.

**Comment by opengeek** [comment]
Merged into 2.5.x and 2.x
