### ISSUE TITLE
Do not jump to an item when searching

### ISSUE THREAD

**Issue by ychelovek** [modxcms/revolution#13420]
### Summary
When searching in a manager, it does not go to the found item

### Step to reproduce
In the control panel header, click the search button and enter the number 1. Find the resource. Try to go to the resource found.

### Observed behavior
Do not go to the found item (chunk, resource, template, etc.)

### Expected behavior
Go to item edit

### Environment
MODX version 2.5.6.
In previous versions, everything worked

**Comment by rtripault** [comment]
Thanks for your report. 

I believe this is related to #13416, #13404 and #13405 (and fixed, a new 2.5.7 release is planned). Sorry for closing those issues.

I guess we will let that one open to prevent additional issue.

**Comment by Jako** [comment]
Fixed with https://github.com/modxcms/revolution/pull/13405

You could replace the following files (manager/assets/modext/modx.jsgrps-min.js, manager/assets/modext/widgets/core/modx.searchbar.js) with the ones of that commit: https://github.com/modxcms/revolution/commit/ca5a9139e33cfa494fb03eb1cf71bd2e379b341a
