### ISSUE TITLE
Mediabrowser session expired

### ISSUE THREAD

**Issue by fozzya** [modxcms/revolution#13441]
### Summary
When I'm trying to upload a file using CKEditor's feature image/Select from server, MODx reports that session expired and a I need to log in again.

### Step to reproduce
CKEditor -> add image -> open browser -> here we are

This issue was found after upgrade to 2.5.5 - 2.5.7 on a different sites.
I've checked the old one site under 2.5.2 - it works perfectly, no issues with session expiration.
Maybe some other stuff like TineMCE etc confirm the issue too.

### Environment
MODX Revo 2.5.5 - 2.5.7 /PHP 5.6/7.0 / MySQL 5.6 / Nginx 1.10/ Centos 7

**Comment by OptimusCrime** [comment]
Do you have basic auth enabled on your server?

**Comment by fozzya** [comment]
> Do you have basic auth enabled on your server?
Yes.

**Comment by OptimusCrime** [comment]
I had this problem with a website that was behind basic auth before too. The reason was that one ExtJS connector call used the old connector format, which for some reason triggered basic auth to require new login. Do you experience this without using extras too? I can not recall just where I experienced this error, so I am unable to reproduce it now.

**Comment by fozzya** [comment]
Thanks a lot for showing me the way. I've found the bad extra. That was modxTalks.
