### ISSUE TITLE
[Bug] manager->lexicon not show new language

### ISSUE THREAD

**Issue by FerX** [modxcms/revolution#13457]
### Summary
Language management does not display all translation languages.

### Step to reproduce
I installed the "SimpleSearch" extra package.
In manager-> lexicon select namespace "sisea"
Added new translation for a language that is not present. (Italian in my example)
Translation works but does not show the new language in the list of languages.

### Observed behavior
The getLanguageList method in core/model/modx/modlexicon.class.php create list of languages supported by that namespace read only on disk and not in the database.

### Environment
MODX 2.5.7, apache, mysql.

**Comment by gernotebenlechner** [comment]
Checking if this issue is valid at #modxbughunt with a fresh 2.5.8-dev install. 

New language for the SimpleSearch extra in core/components/simplesearch/lexicon/ shows up immediately in Manager --> Settings --> Lexicons --> namespace "sisea" within a MAMP instance.

BTW: for a remote server (2.5.7, Apache, MySQL) it shows up immediately after upload in Manager --> Settings --> Lexicons --> namespace "sisea", too.

Result: I **can NOT confirm this issue**.

**Comment by gpsietzema** [comment]
@modxbot close

#modxbughunt #1point to @gernotebenlechner

**Comment by FerX** [comment]
I apologize but I did not explain it well.
**The new language is added from the panel, and then inserted into DB.**
The **getLanguageList** method in core/model/modx/modlexicon.class.php create list of languages supported by that namespace **read only on disk** and not in the database.
If I then insert a new language from the panel (and not on disk) does not appear.

**Comment by Mark-H** [comment]
Thanks for the additional details!

**Comment by wuuti** [comment]
If this was already integrated into 2.6.0, this issue can be closed, right? @OptimusCrime

**Comment by OptimusCrime** [comment]
I think so, yes. 

@modxbot close
