### ISSUE TITLE
Files and Media Browser - Add alert if a folder is moved

### ISSUE THREAD

**Issue by FerX** [modxcms/revolution#13606]
### Summary
In Files and Media Browser accidentally the user can drag a folder into another without notice.

### Step to reproduce
In Files and Media Browser try to move a folder into another folder.

### Observed behavior
Do not alert or ask for confirmation for the move.

### Expected behavior
Ask confirmation for the move.

### Environment
MODX Revolution 2.5.7,  All browser.

**Comment by Jako** [comment]
Addidtion: Disable the confirmation by a cookie for the next 5 minutes with a checkbox in that confirmation window.

**Comment by OptimusCrime** [comment]
Are we sure about this? Do we really want to alert the user if they move files? This does not happen in any operating systems not other web based file managers I have every used.

Not a fan of this.

You COULD highjack the event and disallow it using events and plugins if you really want. Global warning for all users is not a good approach for handling this in my opinion.

**Comment by FerX** [comment]
my customers continue to move folders to other folders, creating malfunctions.

**Comment by whitebyte** [comment]
Do we have granular permissions for file operations? Is it now possible to restrict moving files?

**Comment by OptimusCrime** [comment]
I dont think that is possible with todays system, as both moving and renaming uses the same processor. However, this might be a better approach, as I can already hear the thousands of users getting annoyed that they are asked to confirm yet another intended action.

Instead of developing for the minorities, it is usually best to develop for the majorities and create special systems or functionality for the rest. As I suggested with creating a extra that takes care of this. In fact, I have almost created an extra that handles/takes care of checking broken references due to moved files/images. I am going to open source this some time.

**Comment by alroniks** [comment]
Closed as a wontfix.
