### ISSUE TITLE
Use sprut.io frontend for modx 3.0 Filemanager

### ISSUE THREAD

**Issue by SintezCode** [modxcms/revolution#13694]
### Summary
Change filemanager to sprut.io based on ExtJS
https://github.com/LTD-Beget/sprutio-frontend
https://sprut.io/en/features

**Comment by bezumkin** [comment]
We already integrated this manager at https://modhost.pro and I can`t imagine how this can be integrated into the CMS.

Beginning from the only docker package and ending with requirement to run as root. And, by the way, this uses our lovely ExtJS!

**Comment by Mark-H** [comment]
Agreed with @bezumkin. I don't see how this can be integrated. While it looks cool, and MODX3 can definitely use some more flexibility with the file manager (it's been proposed to make it pluggable, so that extras could implement different variations for different needs), sprut.io looks like something that runs standalone with various infrastructure requirements that are way beyond what MODX asks for. I can't imagine this happening, so am closing the issue.
