### ISSUE TITLE
Modx 2.6.1 Snippet is not working from chunk & cache issue

### ISSUE THREAD

**Issue by chetanpatel** [modxcms/revolution#13732]
### Summary
I am getting strange behaviour of Modx after upgrading to 2.6.1. Its not working properly when I call snippet from chunk. Same is working in 2.6.0 version.

### Step to reproduce
I won't be able to give exact steps as this behaviour is completely happening random.
1) Changing text in snippet.
2) Click save, doesnt make any difference in frontend.
3) I am deleting all cache but still its not making any difference.

### Observed behavior
Competely random behaviour. It changes in frontend sometime and sometime not.

### Expected behavior
It should take latest changes all time as we have selected delete cache option in chunk/snippet.

### Environment
Modx 2.6.1, Apache. php-fpm

**Comment by Mark-H** [comment]
This could potentially be related to mod_security rules, especially the "it
happens randomly" bit. Perhaps you're adding certain text some of the time
that triggers a mod_security rule. Result is it wont update in the database
and won't be shown in the frontend either.

Try asking your host or server admin about it. If they can whitelist
/connectors/ and /manager/, that will help prevent similar issues in the
future.


Op 1 jan. 2018 4:34 p.m. schreef "chetanpatel" <notifications@github.com>:

Summary

I am getting strange behaviour of Modx after upgrading to 2.6.1. Its not
working properly when I call snippet from chunk. Same is working in 2.6.0
version.
Step to reproduce

I won't be able to give exact steps as this behaviour is completely
happening random.

   1. Changing text in snippet.
   2. Click save, doesnt make any difference in frontend.
   3. I am deleting all cache but still its not making any difference.

Observed behavior

Competely random behaviour. It changes in frontend sometime and sometime
not.
Expected behavior

It should take latest changes all time as we have selected delete cache
option in chunk/snippet.
Environment

Modx 2.6.1, Apache. php-fpm

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/revolution/issues/13732>, or mute the thread

**Comment by Mark-H** [comment]
Closing due to lack of feedback and possibly mod_security issue.
