### ISSUE TITLE
Access settings don't work correctly

### ISSUE THREAD

**Issue by salamanderer** [modxcms/revolution#13821]
### Summary
All users what can "edit and save snippet", "edit and save resource" also can use PDO queries.
No matter if they don't have access to change and see system settings, they can change them!
(P.S. Also user can assign yourself as administrator with sudo rights by the same way).

### Step to reproduce
Create not-sudo user. Give him opportunity to edit and save snippet, edit and save resources. Don't give him opportunity to change and see system settings.
Login as user with limit rights, create resource (content = snippet), write the snippet with the following text:

$sql = "update modx_system_settings set value='New Site Name' where key='site_name'";
$stmt = $modx->prepare($sql);
$stmt->execute();

Open the resource in your browser and refresh the manager panel. 

### Observed behavior
The site name has become "New Site Name".

### Expected behavior
The site name (or anyone system setting) must not change.
If PDO queries crush the modx system they must be not allowed for not sudo user at least.

### Environment
Any.

**Comment by Bruno17** [comment]
As soon, as they can write php-snippets or php-files, there will allways be ways to manipulate the db.
If you don't want that, don't give them permissions todo so.

**Comment by Bruno17** [comment]
For the Sudo thingy, there is this one:
https://github.com/modxcms/revolution/pull/13807

**Comment by OptimusCrime** [comment]
This is to be expected in my opinion. Access to snippets, plugins or files gives access to anything. Trying to restrict that is a non-deterministic problem that is impossible to solve.

**Comment by salamanderer** [comment]
Hmm... who said about files? A developer in my system has only access to folder "/assets". 
And user can manipulate db if he has access to db with according rights.
I see the decision of problem in separate db user which will be connected with cms user.
Now all operations in Modx perform across 1 db user.

Suppose, it is not the decision, ok.
But then I repeat - for what access settings need, if every user (with rights to edit and save snippet, to edit and save resources) can change it himself?

**Comment by Mark-H** [comment]
Perhaps it should be more clearly stated in the security/ACL docs, but as soon as you let someone execute PHP code, that should be considered handing over the keys to the full site. 

Even if MODX were to limit the $modx->prepare method from your example, someone could just as easily create their own mysql connection with the DB credentials that are stored in the configuration file. There just is no way to stop someone that can execute code from accessing things like that. 

So you'll have to choose what you prefer. Either you can restrict users from editing snippets and plugins (and PHP/htaccess files, which it sounds like you already did), or you have to accept that they may be able of doing things beyond their MODX permissions through code. I don't see any possible way that can be solved, but am open to ideas...

**Comment by OptimusCrime** [comment]
@salamanderer I said "snippets, plugins OR files". If you give the user permissions to one of these things, you should consider the user being in a position where he or she can get in total control of your site.

@Mark-H explains the reason for this. You should _never_ give a user that you do not trust permission to edit or create snippets. It is really that simple. There is _no_ way to cover all the possible angles and vectors the user might use to gain access to your MODX site. It is simply impossible.

Also not that this problem is not restricted to MODX. If you give a user access to write or alter PHP code in any system, they should (one way or another) be able to gain complete control of the system.

**Comment by sepiariver** [comment]
If a hacker gains the ability to execute arbitrary code on your server, then your server is lost. If you grant the ability to execute arbitrary code, and the user is untrusted, same thing.

If a user who is restricted via ACLs from being able to execute code (no CRUD for Snippets, Plugins, executable file types, Config Settings, nor User records) is able to escalate their privileges, that would be a security issue...

**Comment by alroniks** [comment]
Permissions can not be isolated and equal by the power. Allowing editing snippets (code) means that such permissions just has more power than restricting edit system setting. We can not just by turning off one setting block all other operations in the system. Permission should be atomic and solve one particular case when full protection is a combination (proper combination) of such rules.

I am closing it as seems we got a conclusion, that it is done by design and expected.
