### ISSUE TITLE
Hello, friends! Has anyone encountered such a problem? [2018-03-19 18:56:43] (ERROR @ D:\IT\webserver\domains\stroy-om\core\model\phpthumb\modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: D:\IT\webserver\domains\stroy-om\core\cache\phpthumb\stroy-om__src4630a99a2e39487ff0ce8309777dddbe_parfe75230c38c1dd77cfb659e43ae25583_dat1519131872.jpeg [2018-03-19 18:56:43] (ERROR @ D:\IT\webserver\domains\stroy-om\core\model\phpthumb\modphpthumb.class.php : 133) Error outputting thumbnail: OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618

### ISSUE THREAD

**Issue by batulin** [modxcms/revolution#13823]
### Summary
Quick summary what's this issue about.

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by OptimusCrime** [comment]
Sounds like a permission problem. The webserver is unable to read the original image, and thus fails to generate the thumbnail.

However, we are unable to troubleshoot this further because you failed to provide the necessary steps in the issue template. I am going to close this issue. Please update the issue with the required information and reopen it if you need more help. You could also try a simple [google search](https://www.google.no/search?q=phpThumb+was+unable+to+generate+a+thumbnail). Note: I am pretty certain this is not a MODX problem, but an issue with configuration on your end.

@modxbot close
