### ISSUE TITLE
Content Jumping when loading Manager page

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#14019]
### Summary
It's a cosmetic issue, but the Widget panel is loaded before the resource tree. The Widget panel loads on the left, then jumps suddenly to the right when the tree loads.  This is especially pronounced if any of the widgets take time (especially if the cache has been cleared or there are many resources).

Maybe it would be possible to load the tree ahead of the Widget panel, or load a placeholder for the tree to reserve space for it ahead of the widgets.

### Step to reproduce
Clear the cache when not on the dashboard, then click on the MODX icon.

### Observed behavior
Content jumps to the right

### Expected behavior
Content is stable.

### Environment
Any recent version of MODX

**Comment by alroniks** [comment]
Optionally, but would be good to see the recorded screen with this glitches. It will very helpful to people who fix it to understand what is wrong.

**Comment by jonleverrier** [comment]
I can see what @BobRay reports.

I have recorded a video below. It's hard to spot if you're not paying attention. When you play back the gif frame by frame you'll see no left nav present at around 00:00:02.

![modx_2x_leftnav](https://user-images.githubusercontent.com/2373940/43406413-72e1785c-941c-11e8-8a29-5846be3554da.gif)

I've attached a screen shot of the glitch for reference below:

<img width="1327" alt="screen shot 2018-07-30 at 17 16 45" src="https://user-images.githubusercontent.com/2373940/43406496-a25bf8be-941c-11e8-903c-81f8908aebc6.png">

I think the fix is to add a `min-width` to `#modx-leftbar`. The width of the tree is set inline by javascript, so adding a css min-width might prevent the jump in content whilst the javascript loads and sets the width inline. Similar issue to #13953 that has been fixed.

When I get back from holidays I can take a look at this.

**Comment by BobRay** [comment]
Thanks Jon! What did you use to do the capture?

It's much more obvious on localhost when the cache has been cleared, and UpgradeMODX is checking GitHub to see if there's an update.

**Comment by jonleverrier** [comment]
@BobRay GIF Brewery 3 for mac to record the animated gif

**Comment by jonleverrier** [comment]
@BobRay If you fancy testing or commenting on my PR that would be much appreciated
