### ISSUE TITLE
Stored XSS

### ISSUE THREAD

**Issue by AnusyaAngamuthu** [modxcms/revolution#14094]
Stored XSS: The application is vulnerable to stored XSS.

Step to reproduce

1. Under Media->Media sources choose Create New Media source and enter the Xss Payload <img src=xss onerror=alert("giraffee")> in the Name field and click on save.
2. The application renders the entered script and displays a pop-up whenever the page is being visited by the user.

Observed behavior
The application processes the html tags or scripts and it is getting stored in the database.

 Expected behavior
It should not accept any scripts or html tags.

 Environment
MODX version:MODX Revolution 2.6.5-pl

**Comment by ghost** [comment]
Disagree. In the first place, this can only be done by a trusted Manager login. Access to Media Source management is controlled by ACLs, so lesser-trusted managers are easily excluded. 

In the second place, in a CMS such as MODX, it is a feature that such functions as assigning names or attributes of elements are highly flexible, allowing all sorts of programmatic assignments.

**Comment by Mark-H** [comment]
The manager being a powerful tool should not be an excuse to "disagree" with vulnerabilities. It's a textbook example of XSS vulnerabilities, there's no discussion possible about that. 

I think we all agree it's not the most severe of issues, though. Otherwise @AnusyaAngamuthu would've reported this to the private mailing list.

I looked at a fix for this, but unfortunately it seems that it's not specific to the sources grid. There is nothing specific in `MODx.grid.Sources` that is making this vulnerability possible (e.g. a custom tpl that forgot a htmlent filter like we've seen elsewhere), meaning it goes up the tree to `MODx.grid.Grid` and even `Ext.grid.EditorGridPanel` from what I can tell. Perhaps even beyond that. That suggests practically every grid in the manager may be vulnerable for similar issues. 

There are [some suggested](https://stackoverflow.com/questions/6073037/how-to-escape-html-entities-in-grid) [solutions](https://www.sencha.com/forum/showthread.php?302339-HTML-encoding-grid-data-by-default) on the web to make grids encode by default, but they would likely cause unexpected side-effects in both core and third party components that do expect markup to be accepted (columns that include a link or buttons, for example, would likely also be encoded). Would perhaps be better to address that in 3.0, but that does mean we're leaving the door open to all sorts of XSS issues until then. 

(As a side note, the XSS also affects the Files tree. That should be patched separately.)

**Comment by Omeryl** [comment]
@Mark-H 

Agreed. The problem with stored XSS in the manager is that if a user were able to inject something from the frontend (say, a contact form with a CMP in the manager) they could run javascript code in the context of a sudo user.

**Comment by mrhaw** [comment]
This is an awesome read https://www.markhamstra.com/extjs/

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue and to make MODX better and safer.

It is strongly recommended to not share any known vulnerabilities with the general public and instead [inform the MODX Security Team](https://develop.modx.com/contribute/security/report/).

**Comment by abergmann** [comment]
[CVE-2018-17556](https://nvd.nist.gov/vuln/detail/CVE-2018-17556) was assigned to this issue.

**Comment by AgelxNash** [comment]
I can upload the SVG file with JavaScript. This will also be vulnerability, while CSRF token not yet implemented....

I can upload the ZIP file with PHP file. And then unpack it. Pofit! I uploaded the PHP file!!! It's all different vulnerability, but they are executed from the administration panel...

I think this position will be very useful: https://github.com/robiso/wondercms/issues/57

Even with minimal rights in the administration panel, you can easily elevate the rights to the administrator. Perform arbitrary reading of files, running snippets, reading information from the database, etc. Therefore, XSS through the administration panel is the least evil.

**Comment by mrhaw** [comment]
My 2 cents:
1. Put the effort to make FRED https://fred.modx.com/ secure in this regard. Then it be sweet if we could block access to the regular manager.
2. Utilize front-end and web users before trusting people with Manager logins.

// I setup manager users with very restricted access and lots of Form Customization. I limit access to extras by category etc. It is possible to control most stuff, but still I feel the need to trust the user before letting him in.

**Comment by AgelxNash** [comment]
And again: #14105 #14104 #14103 #14102
Do you want to continue to receive such reports about XSS in the admin panel?

**Comment by attritionorg** [comment]
If the admin role is expected to be able to insert JavaScript, then a) document it on a page by page or feature by feature basis and b) consider putting a one-line warning in the interface on each page, that the admin has that ability and such script can be dangerous. Any subsequent reports of XSS in the admin panel mean the researcher ignored both documentation and warning clearly indicating it is intended functionality.

**Comment by JoshuaLuckers** [comment]
@AgelxNash Thanks for taking time to report this issue and to make MODX better and safer.

It is strongly recommended to not share any known vulnerabilities with the general public and instead [inform the MODX Security Team](https://develop.modx.com/contribute/security/report/).

**Comment by Mark-H** [comment]
I do think we need to have a candid discussion about how secure the manager needs to be. 

My personal guideline for when to worry about vulnerabilities in the manager has always been about if the limited user account on the modmore demo site is enough to do harm/elevate rights/run arbitrary server side code. While that is not the case for the media source name reported in this issue, #14105 might actually pose a risk because a fairly low-level permission is used there.

The only way to truly stop XSS issues from coming up time and time again is to implement security-first rendering. Escape every input, unless it has been specifically marked to be trusted. [There appear to be options for that in ExtJS](https://github.com/modxcms/revolution/issues/14094#issuecomment-424667098), but they'll cause things to break in both the core and extras. Perhaps we need to consider doing that in 3.0 so we can put this to bed, and spend the time we save on dealing with individual XSS issues in the future on fixing the things that the change will break.

**Comment by AgelxNash** [comment]
@Mark-H I think, you can using [Content Security Policy headers](https://en.wikipedia.org/wiki/Content_Security_Policy)

**Comment by Mark-H** [comment]
I've created PR #14344 to apply htmlEncode to all grid columns by default, targetting 3.0.
