### ISSUE TITLE
[bug] Form Customization: order of the fields in "Set Information and Fields" tab, id field

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14226]
### Summary
1) In the "Set Information and Fields" tab (Edit set) of the "Form Customization" section, the order of the fields must be corrected in accordance with the resource editing form:
**modx-resource-main-left
modx-resource-main-right
modx-resource-content
modx-page-settings-left
modx-page-settings-right
modx-page-settings-right-box-left
modx-page-settings-right-box-right**

2) In the "modx-resource-main-left field" there is an "id" field, but it doesn't work. It seemed to me that it is responsible for displaying id in the title of the edited resource, but this is not so.
The "id" field must either be used in the title, or the id field must be removed.

![form_custom](https://user-images.githubusercontent.com/12523676/50547556-3c019180-0c55-11e9-88fe-bacdbd0ef38d.png)

### Environment
MODX 2.7.0

**Comment by alroniks** [comment]
To show id in the title or nor managed by special system setting. So too many places of configuring that behavior sound worth for me than just delete it from FC. But, id field always exists in the resource forms as a hidden field (editing) and FC allows on not this hidden field. So point 2 unrelated I guess, because FC describes forms, not labels or titles of the page.

**Comment by Ruslan-Aleev** [comment]
Fixed in https://github.com/modxcms/revolution/pull/16052
