### ISSUE TITLE
Trash manager context menu only working for sudo user

### ISSUE THREAD

**Issue by travisbotello** [modxcms/revolution#14337]
### Summary
Context menu to "Purge" or "Restore" single resource inside trash manager is not working when user doesn't have the sudo flag. 

### Step to reproduce
- Create a new user group
- Assign Administrator Policy access policy with all permissions enabled
- Assign new user but make sure to uncheck sudo flag
- Delete resource
- Switch to trash manager
- Try right click on a deleted resource

### Observed behavior
Context menu is not showing up via right click.

### Expected behavior
Context menu should be visible via right click.

### Environment
MODX 2.7.0 advanced

- When adding the sudo flag to this user, the context menu is showing up as expected.

**Comment by wax100** [comment]
The problem is (as I understand) in line 130 , file **\core\model\modx\processors\resource\trash\getlist.class.php**
`$canEdit = $this->modx->hasPermission('edit');`
I can't find permission **EDIT**, we have only **SAVE** 
Thats why clients do not see context menu on _manager/?a=resource/trash_ page

**Comment by sdrenth** [comment]
I will fix this

**Comment by Ibochkarev** [comment]
Fixed  #15482
