### ISSUE TITLE
Generate a random prefix in the database during installation

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14792]
### Summary
It would be useful if during the installation of MODX 3 the prefix to the database would be generated randomly, instead of the standard `modx_`. Additional site protection.

**Comment by Jako** [comment]
Not really, if someone has access to the database you have lost already.

**Comment by Ruslan-Aleev** [comment]
I understand it.
But I'm talking about the fact that, knowing the prefix, you can create a query on a specific table, for example, of users, even without full access, such as sql injection.
Probably now it is not very relevant, but you can insure additionally :)

**Comment by Mark-H** [comment]
With a SQL injection, finding out the prefix would be fairly straightforward, especially for non-blind injections, but even with blind injections that could probably be brute-forced or otherwise inferred.

What's important to note in this discussion is that the primary purpose of the configurable prefix is **not** security, but the ability to have multiple installations in the same database (e.g. on a shared host) and/or allow running different systems from the same database by ensuring table names ("users") don't conflict.

People who want a random prefix can already ask their cat to walk over the keyboard during the setup, or whatever their preferred mechanism for generating random strings is, but we don't have to force random prefixes on users.
