### ISSUE TITLE
Rethink colors / contrast manager panel to match WCAG 2 / AA

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14881]
### Summary
The current color scheme does not pass WCAG 2 / AA recommendations.
We need to rethink the colors of the manager panel in future.

https://webaim.org/resources/contrastchecker/?fcolor=ffffff&bcolor=528738

### More details
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
https://make.wordpress.org/accessibility/handbook/design/use-of-color/#about-color-contrast

### Related issue(s)/PR(s)
The problem was partially discussed in https://github.com/modxcms/revolution/pull/14785

**Comment by Mark-H** [comment]
I don't think this requires an issue. Each pull request simply needs to move us closer rather than further away from WCAG AA compatibility. That's a question of process and properly reviewing design changes; not a single task.

**Comment by Ruslan-Aleev** [comment]
>  That's a question of process and properly reviewing design changes; not a single task.

This is clear, but it would be better to leave the issue open, at least, so as not to forget about it and stimulate discussion.

**Comment by Mark-H** [comment]
While I care a lot about accessibility and will happily discuss any proposals or ideas to improve it... An issue like this would _never_ get closed, because there is no actionable task. There are always more improvements that can be made, and I doubt we'll ever be able of reaching full WCAG AA compatibility, at least not until ExtJS has been replaced, and even then it will always be a moving target. 

I simply don't want issues that can never be closed, not when we already have 600+ issues. 

I solemnly swear to you that I wont forget, and will pester everyone that submits a design related PR about moving closer to WCAG AA for as long as I'm part of this project.

**Comment by Ruslan-Aleev** [comment]
I understand. Thanks.
