### ISSUE TITLE
MODX_URL_SCHEME returns invalid value

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15269]
### Summary
`MODX_URL_SCHEME` returns invalid value

### Step to reproduce
Set the value of the system setting `server_protocol` equal to `https`

### Observed behavior
When the system setting `server_protocol` is equal to `https`, the `MODX_URL_SCHEME` variable gives a value equal to `http`

### Expected behavior
When the system setting `server_protocol` is equal to `https`, the `MODX_URL_SCHEME` variable should give a value equal to `https`

If you manually specify the value in the file `core/config/config.inc.php`, then everything is displayed correctly

```php
if (!defined('MODX_URL_SCHEME')) {
    $url_scheme=  $isSecureRequest ? 'https://' : 'http://';
    define('MODX_URL_SCHEME', 'https://');
}
```

### Related issue(s)/PR(s)
NA

### Environment
MODX 2.7.3, Apache/2.4.10, php 7.3.19

**Comment by Ruslan-Aleev** [comment]
The `server_protocol` setting did not work and was removed for the 3.x branch - https://github.com/modxcms/revolution/pull/14877
In general, it is not at all clear why configure the protocol manually? We connect the certificate, specify redirects in the server settings, for example .htaccess for Apache and everything works - the standard behavior. Partly discussed here - https://github.com/modxcms/revolution/issues/13269
For the 2.x branch, we also need to remove this setting, since this setting looks working and confuses users.

**Comment by opengeek** [comment]
The `url_scheme` setting is what needs to be configured to manually change the behavior in the core. You do not need to manually edit the constant defined in the config file. Those changes would be overwritten on upgrade.

**Comment by Ibochkarev** [comment]
> The `url_scheme` setting is what needs to be configured to manually change the behavior in the core. You do not need to manually edit the constant defined in the config file. Those changes would be overwritten on upgrade.

I agree, but on my project it doesn't work as intended.

**Comment by opengeek** [comment]
> > The `url_scheme` setting is what needs to be configured to manually change the behavior in the core. You do not need to manually edit the constant defined in the config file. Those changes would be overwritten on upgrade.
> 
> I agree, but on my project it doesn't work as intended.

To be clear, unless your project is referencing the `url_scheme` setting (via getOption) this will not work. Do not use the constant `MODX_URL_SCHEME` if it is not providing the correct value automatically based on your server configuration.
