### ISSUE TITLE
session_cookie_secure setting will soon be rejected

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#15301]
### Summary
The `session_cookie_secure` system setting is currently a boolean value, with the default being false. This means that on a secure site the session cookie will get set to not secure resulting in the following warning: 

```
Cookie "PHPSESSID" will be soon rejected because it has the "SameSite" attribute set to "None" or an invalid value, without the "secure" attribute. To know more about the "SameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

### Step to reproduce
Access a default install of MODX on a secure domain and check the console log. 

### Observed behavior
The session cookie is set to not secure.

### Expected behavior
If the setting was not adjusted the session cookie's security should be based on the protocol used by the site.  

### Related issue(s)/PR(s)
None so far

### Environment
Any MODX, I've tested on a few 2.6.5+ sites, but guessing this has been an issue for a while.

**Comment by Mark-H** [comment]
This has more to do with SameSite than Secure - MODX doesn't currently have support for SameSite which comes with some unique BC/support complexities..

**Comment by opengeek** [comment]
> This has more to do with SameSite than Secure - MODX doesn't currently have support for SameSite which comes with some unique BC/support complexities..

It seems it would not be an issue if the cookie was marked secure, which it should be since it was on an https connection. There should not be a default value in system settings for ANY of the cookie settings, to be honest.

**Comment by opengeek** [comment]
But it seems there is no way to provide a blank value for a "boolean" xtype.

**Comment by sergant210** [comment]
I think this system setting should be defined at the time of installation.

**Comment by matdave** [comment]
After further thinking about this, I wonder if it would make sense to be part of the configuration check. A warning that pops up if the setting is no, but the site is on HTTPS. It appears the default behavior if it is just left empty is to set it to no, so it makes sense to keep the boolean option.

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-session-cookie-with-samesite/3927/2

**Comment by jcdm** [comment]
We have a solution to the version check and correct settings here with a solution that also includes a system setting:
https://community.modx.com/t/modx-session-cookie-with-samesite/3927/5

What this doesn't have is a solution for sub 7.3 so that it works there. One option would be to dig up the header required and send that from the right place in the code base. The other option would be to mark it in the system setting description as "only functions in PHP 7.3 and above".

Will depend what the MODX policy is on "support for versions of PHP" - does that mean feature complete or is it OK to exclude functionality in edge cases?
