### ISSUE TITLE
Possible mysql injection

### ISSUE THREAD

**Issue by MrRoco** [modxcms/revolution#15305]
### Summary
Within a getObject call where the argument is a string, so based on primary key, mysql manipulation is possible.
It seems it only is able to execute string, numeric or date functions for selects. I've tried to debug is it's possible to delete, truncate or manipulate data within the DB and was unsuccessful (A little Yeey..)

### Step to reproduce
Do a get object like: $modx->getObject('modContext', 'if(now()=sysdate(),sleep(20),0)');

### Observed behavior
The DB query goes in sleeper mode for 20 seconds.

### Expected behavior
Return an error.

### Related issue(s)/PR(s)
None found so far.

### Environment
Modx 2.8.
Php 7.3.

**Comment by Mark-H** [comment]
For reporting vulnerabilities responsibly please use security@modx.com. 

The getObject method indeed supports a wide range of syntax for the second parameter - basically an xPDOCriteria or anything that can be parsed into an xPDOCriteria, like an array or a mysql string. That's known and expected behavior. 

That's also why you shouldn't do something like `$modx->getObject('class', $_GET['id'])` but always be explicit about the type of criteria you're providing, i.e. `$modx->getObject('class', ['id' => (int)$_GET['id']])`. I'd say that's public knowledge ever since 2.5-ish, but as the documentation for getObject does not explicitly state that I've logged a [documentation issue](https://github.com/modxorg/Docs/issues/230). 

If there are parts of the core that allow arbitrary user input into the criteria parameter, please report such issues responsibly via security@modx.com.
