### ISSUE TITLE
MODX3 - Removing a widget from a dashboard does not work

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15324]
### Summary
Removing a widget from a dashboard on the dashboard management page does not work in current MODX3.
i.e. `/manager/?a=system/dashboards`

Note: it does work if you close a widget when on the dashboard itself.

### Step to reproduce
1. Go to the dashboards page `/manager/?a=system/dashboards` and create a new dashboard. Add some widgets, and save.
2. Go to the ACL page `/manager/?a=security/permission` and right click on the Administrator group, then select `Edit User Group`.
3. Select the new dashboard for this user group and save.
4. Go back to the dashboard and see you are using the new one.
5. Return to the dashboard management page `/manager/?a=system/dashboards` and remove a widget. Save.
6. Return to the dashboard and see that the widget was not removed.

### Observed behavior
Widgets are not removed if done from the dashboard management page. Only works from the dashboard itself.

### Expected behavior
Removing a widget from a dashboard should work if the option is there for it.

### Environment
MODX 3.0.0-alpha3, PHP 7.4, Mysql 8

**Comment by theboxer** [comment]
@digitalpenguin so the reason why it still shows is because if the dashboard is marked as customizable, it clones all the widgets with a reference to a user, when user loads the dashboard. Later when you are making changes to this dashboard (remove/add - same issue will happen with add), it only adjusts the dashboard for user `0` - for anyone who didn't open the dashboard yet and have their clone.

I'm not sold on if this is or is not an issue, but I created a PR in case more ppl will think this is a bug.

**Comment by muzzwood** [comment]
Ah I see. Thanks for creating the PR in any case!

Perhaps just the wording will need to be updated on the dashboard management page, to indicate that it only affects the initial state of the dashboard. Otherwise unaware users will be wondering why their changes aren't visible.

Maybe a button that shows a view of how the dashboard looks when not marked as customizable.
This is obviously a low priority issue compared to others.

Does anyone else have any thoughts on this?

**Comment by theboxer** [comment]
I'm torn on what's the correct approach for  this - that's why I created the PR :) It will only add/remove the widgets that you are adding/removing from the dashboard and leaving the rest untouched.

So if you have dashboard with widgets A,B,C. User removed widget A from their dashboard and admin goes and add widget D. The user will see widgets B,C,D.

**Comment by Ibochkarev** [comment]
Fixed #15390

**Comment by mkschell** [comment]
fwiw opened PR to update Docs to include this change, among others: https://github.com/modxorg/Docs/pull/562
