### ISSUE TITLE
Improve changelog rendering in the package manager

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15439]
### Summary

![Schermafbeelding 2021-03-04 om 16 55 16](https://user-images.githubusercontent.com/312944/109991322-846fda80-7d0a-11eb-8980-526c32ec6452.jpg)

### Step to reproduce

Install a package with a markdown changelog like ImagePlus. In the rendered changelog there is no clear visual hierarchy for version numbers, subsections etc. See screenshot above. 

### Observed behavior

See screenshot above.

### Expected behavior

Should look better - better headings and categorisation, appropriate margins etc. 

### Related issue(s)/PR(s)
N/a

### Environment
Any

**Comment by Ibochkarev** [comment]
The parser generates incorrect markup, since the markup is not correct in the changelog.md file.

For example:

```html
<ul>
<li>Updated jQuery</li>
<li>Fixing a jQuery issue with ContentBlocks and other extras that use jQuery inside [#60]</li>
<li>Fixing cannot read property 'destroy' of undefined issue</li>
<li>Fixing Undefined property issue [#71]</li>
<li>Fixing a window issue with really small images [#53]
<h3>Removed</h3></li>
<li>Some IE &lt; 9 CSS rules</li>
</ul>
```

There must be an empty line after lists, code, headers (`<h3>Removed</h3></li>` - Goes to a list item because there was no empty line after the list)

If you run through the markup linter (which I did), you can see all this. Accordingly, you need to use a linter and follow the markup rules for mardown. 

https://github.com/Jako/ImagePlus/pull/90/commits/1829b0e9adacd4fea3caf345ae471ad5d2a92085

Parsedown - generates correctly.

I'll make some cosmetic styling tweaks.

@Jako I ask you to accept the PR, build the package and put it in the repository

**Comment by muzzwood** [comment]
Hopefully this could parse markdown too

**Comment by Mark-H** [comment]
> The parser generates incorrect markup, since the markup is not correct in the changelog.md file.

I probably should have checked that first 👀

**Comment by Jako** [comment]
Thanks. Then there is also an issue in https://keepachangelog.com/en/1.0.0/

**Comment by Ibochkarev** [comment]
Improved in #15486
