### ISSUE TITLE
Media Sources and folder name with accent

### ISSUE THREAD

**Issue by pelargo** [modxcms/revolution#15659]
After the update from 2.7.3 to 2.8.1, the folders whose name has an accent in assets/ are no longer accessible by Media Sources (cannot display the files or right-click on the folder)

**Comment by Ruslan-Aleev** [comment]
This is also actual for MODX 3, for example, you can create a folder named `őőő`, although if you name the folder `site-őőő`, then there are no more bug (although maybe I didn't quite understand the issue).

**Comment by black-meridian** [comment]
an example, we can list files from the folder "communication GT7" :
![Capture d’écran 2021-07-01 à 12 02 47](https://user-images.githubusercontent.com/36260542/124106154-3d011d00-da64-11eb-8380-ec0b7a9a51eb.png)

but, there is a bug with the folder just under, "entreprise adaptées", because of the accent, on click, nothing appears

**Comment by niepro** [comment]
Same problem here with umlaute (äöü) in MODX 2.8.1 on MODX Cloud.

**Comment by matdave** [comment]
Found the issue. It is fixed in 3, and should be fixed in 2.x with the above referenced PR.

**Comment by black-meridian** [comment]
I did a test with the new file, and everything is fine. thanks!

**Comment by Ibochkarev** [comment]
Fixed #16071
