### ISSUE TITLE
Empty fields in the TV quick edit form

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15947]
### Summary
Empty fields in the TV quick edit form:

![tv_qe](https://user-images.githubusercontent.com/12523676/147387186-fd4eba4f-f3b4-4032-852d-35d379362038.png)

### Related issue(s)/PR(s)
Probably https://github.com/modxcms/revolution/pull/15773
https://github.com/modxcms/revolution/issues/15854

### Environment
MODX 3

**Comment by Ruslan-Aleev** [comment]
@smg6511 Check, please

**Comment by smg6511** [comment]
@Ruslan-Aleev - Quick question on this (for others too): Would it be an option to _not_ include the default value and options fields in the quick create/edit form? I ask because that's a very simple fix that I was going to propose at some point. The tricky part here is integrating the tv type-aware display (and hiding) of these fields — which I'd developed for the main TV editing page. The issue there is that, as it stands, the TV panel class is only loaded for the main TV creation/editing page. Thus the lexicons and methods used there are not available elsewhere. It's an issue that can be overcome with some rethinking of where some of the TV methods are placed (perhaps moving them into the main modx class or in the utilities file).

Otherwise, a temporary quick fix would be simply to re-introduce the needed lexicon entries into the default file and not worry about the TV type-specific configs right now.

**Comment by Ruslan-Aleev** [comment]
> Otherwise, a temporary quick fix would be simply to re-introduce the needed lexicon entries into the default file and not worry about the TV type-specific configs right now.

I think this option is preferable (at least for now).
Moreover, this is already relevant for the lexicon "The name to show beside the input when editing a TV on a Resource form."

**Comment by Ibochkarev** [comment]
Fixed #15951
