### ISSUE TITLE
Manager menu in french is not effective

### ISSUE THREAD

**Issue by revocarne** [modxcms/revolution#15990]
### Summary
In the french manager menu, the "Manage" menu is translated to "Administration". It's to large for the menu and an horizontal scrollbar appear in menu bottom.

**Comment by Mark-H** [comment]
I'm not sure what a better (shorter) name would be, but that can be corrected in the French translation via crowdin: https://docs.modx.com/current/en/contribute/translate

**Comment by revocarne** [comment]
Yes, but the problem is only for 2px, it's eventually possible to modify a little the css?

#modx-header -> "width: 72px;" (instead of instead of "width: 70px;") work great
or
#modx-navbar -> "padding: 0 3px;" (instead of instead of "padding: 0 5px;") work great

This modification work great for MODx in French and it's not a big modification!?

**Comment by revocarne** [comment]
another css way is the overflow, because I think the navbar won't is used with long button text.

#modx-navbar: overflow: hidden;

**Comment by Ruslan-Aleev** [comment]
@revocarne It is not practical to edit the MODX template for any language. Because in one language it will be displayed well, but in other languages it will break.
Correct the translations at https://crowdin.com/project/modx-revolution for your language (request access and new MODX versions will have your correct translation) or correct the translations on your site, in the manager.
