### ISSUE TITLE
MODX3 RC1 install fails on chrset change to UTF8 / UTF8ci

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#16003]
### Summary
MODX3 still does not honor charset changes. As I have stated before latin is too limited and other charsets should be usable - especially when they are listed in the dropdown. This is not a new issue.

### Step to reproduce
Change Charset to UTF8 / general-ci.

### Observed behavior
Database test
Failure message. No error was provided (on screen or filesystem)

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version: MODX Revolution 3.0.0-rc1 (traditional)
Version codename: Revolution
Database type: mysql
Database version: 10.2.41-MariaDB-cll-lve
Database charset: latin1

**Comment by Mark-H** [comment]
This is an upstream issue https://github.com/modxcms/xpdo/issues/175 - closing it here. 

While it is true xPDO doesn't currently actually set the charset/collations even though it could (there's a patch here: https://github.com/modxcms/xpdo/pull/192), the reason it's using latin1 is because the database was created with latin1 (or the server default of latin1). If you create the database properly before running the setup that will avoid this issue.

(Also very strongly recommend utf8mb4 over utf8 so you can use ✨ emojis ✨ but that's kinda off-topic)

**Comment by JoshuaLuckers** [comment]
@wshawn Thanks for bringing this up again

**Comment by wshawn** [comment]
> 1 is because the database was created with lati

I actually created the database with UTF8, not Latin. I create all my international databases in UTF8, as I really do not have any options. Thank you for looking into this. I have been busy converting some projects to Laravel 9 and failed to see this earlier.
