### ISSUE TITLE
When using an output filter on template, filter don't work

### ISSUE THREAD

**Issue by Ayddan** [modxcms/revolution#16197]
### Summary
When using output filter on template, result is the template number like if filter was not apllied.

### Step to reproduce
using this syntaxe in a chunk/template
````[[*template:in=`33`:then=`html`]]````

### Observed behavior
Rendering the template number instead of html in condition
<img width="89" alt="image" src="https://user-images.githubusercontent.com/72895585/171351748-7fd82143-6480-4519-aacf-8f22e149d5ac.png">

### Expected behavior
Should render html in condition if template number is in list

### Environment
MODX 3.0.1, apache 2.4.47 , mysql 5.7.33

Maybe link with ? https://github.com/modxcms/revolution/issues/16186

**Comment by halftrainedharry** [comment]
I can't reproduce this.

**Comment by JoshuaLuckers** [comment]
I'm also not able to reproduce this behavior. I've used the example in a template, chunk and in my content and they all produce the same empty output if the ID of the template doesn't match the `in`. 

@Ayddan does it also happen if you create a new template that only contains your example code? Does this also happen if you use `id` instead of `template`?

**Comment by Ayddan** [comment]
I've tried to run this code in a new template and it works with both id and template. Probleme seems to be in my template. I will dig a bit more.

**Comment by Ayddan** [comment]
This problem seems to be related to [#1445](https://github.com/modxcms/revolution/pull/14458). My html in the "then/else" contain pthumb with options and the problem disapear if i cut this part. So i close this issue.
