### ISSUE TITLE
"Site temporary unavailable" an error occurs during installation with a certain character in the password

### ISSUE THREAD

**Issue by obelov** [modxcms/revolution#16261]
### Summary
About MySQL passwords, contains "\\" symbol and incorrect character processing "\\"

### Step to reproduce
during the installation step in the "MySQL user password" field, enter the password containing the character "\\"

### Observed behavior
After clicking the "install" button, an error is thrown "Site temporary unavailable"
In the config file "/core/config/config.inc.php" MySQL password contains an extra character "\\\\"

### Expected behavior
a message should appear : "Core installation was successful. Click next to complete the installation process."

### Environment
MODX version 3.0.1 Advanced, Apache, MySQL 10.5.16-MariaDB, Firefox 104.0.2

**Comment by halftrainedharry** [comment]
The problem seems to be this line in the code:

https://github.com/modxcms/revolution/blob/f7bc0133f5f09184418a7ddf6f9b98a3f0decd9e/setup/includes/runner/modinstallrunner.class.php#L170-L177

I don't think the problem is the double backslash in the config file `\\` (as the backslash is an escape character).
I think the problem is that the settings is changed here (to write it correctly to the config file), but this (changed) setting is then later used again in the installation script.

**Comment by JoshuaLuckers** [comment]
Are you sure the error is related to the password? Is there anything in the MODX and/or PHP error log?
