### ISSUE TITLE
Single property set has a + next to it in Property Sets

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#1757]
bobray created Redmine issue ID 1757

I thought the plus might show the property set's description. but it doesn't. When you click on it, it disappears.

**Comment by OptimusCrime** [comment]
In Property Sets the triangle at the left side of the property set now behaves the same as the triangles in the menu (both resources and elements). It lists the sub elements for that parent. I think the behavior here is clear enough.

The activity here would suggest that this is by design or wontfix. 

Closing this due to old age and lack of activity. Feel free to reopen or comment if you feel otherwise.

@modxbot close
