### ISSUE TITLE
Property sets to support nested categories

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#2731]
andy@andyshellam.eu created Redmine issue ID 2731

I have the following category layout:

- Generic
- Main Site
- - Home Page
- - Search
- Media

In the elements list, this is shown correctly as nested (i.e. expand Main Site, then I can see Home Page and Search.)

However in the Property Sets dialogue, these categories are flattened, so I see:

- Generic
- Home Page
- Main Site
- Media
- Search

I think this should be consistent across all screens that use categories - i.e. they should all be nested.

**Comment by adamwintle** [comment]
@ghost Due to inactivity I'm going to close this item - I'm also not 100% which "Property Sets dialogue" you're referring to. I checked the Template Property Sets and also the main Property Sets CMP and neither have a tree view which is the same as the main Resources tree. 

If you can provide more info or a screenshot then we can reopen the issue.

@modxbot close
