### ISSUE TITLE
Combined view of all elements and dividet view for context

### ISSUE THREAD

**Issue by theuros** [modxcms/revolution#2899]
theuros created Redmine issue ID 2899
1. I'd like to have an option to see all elements from one category like in modx evolution. 
   With big pages and lot of elements becomes difficult to find them. If you have a lot of chunks wich depends on  snippets .. it's a nightmare to find them one or another for editing ... 
2. If you create a multisite and you  use a lot speciffic elements for each context you get too many of them. It will be nice to have a possibility for elements to define for wich context are  (one contex,more context or general for all) ... and of course to have an ability to display only elements of speciffic context.

**Comment by alroniks** [comment]
The first issue fixed in this PR #13997
About the second issue, I don't agree because chunks, snippets etc - it is a code that should be independent and common for all user data. And in future, they will go into the files and it will be difficult to link them with entities in the database. Contexts are user data.
