### ISSUE TITLE
Disk space and transport packages

### ISSUE THREAD

**Issue by boomerang** [modxcms/revolution#3375]
boomerang created Redmine issue ID 3375

I noticed today on one of my very small website that my disk space had jumped dramatically even though I have added nothing much in the way of actual content to the site.

On further investigation I discovered that the transport packages for the various snippets including all the updates were taking up a huge amount of disk space - what is the best way to prevent this occurring other than deleting previous versions?

For those clients who do not have particularly high disk space on their servers this could pose quite a problem.

Couldn't find anything regarding this issue in the forum, so I have decided to bring it up here as I feel this could be a fundamental problem especially with the number of updates to various snippets as we all move forward.

**Comment by rtripault** [comment]
Since this is the intended behavior, gonna close this one.

On an another hand, i could definitely see a component (or something shipped with the core), that would allow some kind of auto cleanup (ie. keep last x version(s) of each components).

Feel free to comment/reopen if you feel the need.
Thanks
