### ISSUE TITLE
changing policy template for access policies

### ISSUE THREAD

**Issue by u007** [modxcms/revolution#3395]
u007 created Redmine issue ID 3395

Hi,

ive tried to add in a custom policy in the access policies, and i realized that i couldnt do it without adding it in the policy template.
Is there a way to change the policy template of an existing access policies without editing the database table?

Or maybe its possible to add in custom policy name into access policies without involving changes on the policy template..

please advice,

thank you.

**Comment by alroniks** [comment]
You can just add (at least in current 2.6.4 version) new Policy Template and add to it any permissions that you want. And after that create new Policy based on this Template and select needed permissions. So templates for creating lists of permissions, policies for configuring such lists.
I am closing it because nothing to fix. But if you have questions, please, ask. I will try to help.
