### ISSUE TITLE
Ability to assign Default Template for Weblink, symlink, static resource

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3560]
onepack created Redmine issue ID 3560

There is the ability to assign a default template for Resource Documents.
It would be great if there would be a possibility to assign a default template for a Weblink too.

To illustrate this. Editors would hardly use the field Link Attributes in a resource template so I hide it with form customizations for the used templates.
Now in a weblink it is required to have this field but the system loads the standard (Detail) Template (set in the system settings) where I'm hiding this field. I would like to assign the "empty" or a custom made template for weblinks were I'm not hiding the Link Attribute field.

Another possibility would be to select a field in Templates for what kind of resource document you assign the template.. Weblinks, Resource Documents... etc.

**Comment by OptimusCrime** [comment]
I tried accomplishing this using form customisation.

- Constraint Field: `class_key`
- Constraint: `modWebLink`, `modDocument` and so on

This worked like a charm!

Because the age of this ticked and no planned goal to implement several system settings as suggested by @Mark-H I am closing this for now. Feel free to reopen.

@modxbot close
