### ISSUE TITLE
Form customization for BOTH update and create

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#3772]
ncrossland created Redmine issue ID 3772

It would be useful if there was the ability to create a rule for BOTH the update and creation of resources - it's very rare I'd want to do something different, and would remove a lot of duplication of effort in setting up every rule twice.

**Comment by neoneddy** [comment]
+1 on this.

**Comment by gpsietzema** [comment]
+1 from me as-well.

There's an important thing though: can there be situations where you want different rules for create and update? I can't think of any right now. But if there are, this isn't a good idea.

Any ideas?

**Comment by pixelive** [comment]
+1

**Comment by OptimusCrime** [comment]
Please take a look at answer given earlier:

>splittingred submitted:
>While nice in theory, this does not work pragmatically - constraints are impossible to apply without separated create/update rules.
>If I set a constraint of 'template' => '4', one would assume that means don't do FC rules except on Resources with Template of 4.
>However, on a 'Create Resource' page, no new resource has a template of 4 (unless done via a default_template setting or another FC rule). So, currently, FC gets around this by having Constraints apply to the parent of the newly made Resource. This could not be done without separation of update/create.

I think is good enough reason to close the request, unless someone with good knowledge in the implemenation can tell if doing a workaround could be possible without redoing too much of the code. I have never looked at how FC is implemented "under the hood", so I can't tell.

**Comment by gpsietzema** [comment]
That's not a reason not to do it. If a rule has a constraint for template==4 and you're creating a resource where template==4 doesn't apply, it just doesn't work. That's that.

There is a possibility to build in something like template inheritance. We use a plugin for this: when creating new resources it checks a system setting for template inheritance, based on the parent template.

This could be something for a new MODX release I guess. We'll how we can implement this.

**Comment by isaacniebeling** [comment]
I'm with @gpsietzema on this one... If it doesn't apply, it doesn't apply, but keeping update and create rules in sync has had me tearing out my hair on more than one occasion. As long as FC is (one of) the last bits of JS to fire on resource load, it should be able to cover just about any constraint the same on Create as on Update.

**Comment by rainbowtiger** [comment]
Wouldn't it be easy enough to just add a third option? "resource/create", "resource/update", and "resource/create or update"? One would assume that programmers won't be trying to add constraints that don't apply if "resource/create or resource/update" is the selected option. Then, when the manager is grabbing customizations to alter the layout, it would, for example, look for (resource/create OR resource/create or update) instead of just (resource/create), or however this works behind the scenes. This problem is near the top of my list of headaches in MODX. I've never, EVER, needed to use different setups for creating and updating resources in the hundreds of websites I've created, and it's a pain to have to edit two different customization settings every time I need to update an existing manager customization.

There MUST be a way to do this, using some creative thinking. As for constraints, if this is really such a problem, how about having TWO constraints fields, one for create and one for modify? Then MODX would use the appropriate one. Or, as gpsietzema said above, if an entered constraint doesn't work, it just won't do anything, so what's the problem?

**Comment by Mark-H** [comment]
The Form Customization is not really a simple feature, so while it's easy to say how it should work, it's a bit tricky to implement.

I do agree that if possible it should be a new option ("both") as that sidesteps backwards compatibility issues and still allows different options for create/update for those that want it. 

Maybe I'll take a look later when I'm waiting for my flight to see what I can do...

**Comment by Mark-H** [comment]
Some notes from my looking into this... for each rule (stored as modActionDom object, cause naming logic) the for_update column is being set to 1 along when controller is resource/create. The modManagerController->checkFormCustomizationRules method filters rules on both the controller and the for_update, but I've not really found any particular reason for this for_parent column in the source. It's only used in the loading of rules as far as I can tell, and also not exposed in a UI anywhere. 

I'm thinking that we should get rid of the for_parent check, and instead should change the filter so it can do a `IN (resource/create, both)` type filter instead.

**Comment by Mark-H** [comment]
Managed to get it to work! #13775

Testers would be much appreciated ;)

**Comment by rainbowtiger** [comment]
I've got a non-production site right now I can test this on.

**Comment by rainbowtiger** [comment]
This seems to be working just fine. I wonder, though, why you chose to use a wildcard ('/*') rather than something like "/both". I tested your way, then changed to "/both" through and that seems to work just as well, plus I think it's nicer to see 'resource/both' in the Action column when viewing the list of customizations rather than 'resource/*'.

**Comment by Mark-H** [comment]
The list of sets is already updated to show the lexicons, unless we're talking about a different page? 

I went for the wildcard instead of /both as it is technically a wildcard. `resource/*` will also match a `resource/foo` action, if that would exist.

**Comment by rainbowtiger** [comment]
I'm talking about this screen:
![profilescreen](https://user-images.githubusercontent.com/2528374/36080235-133f3dee-0f5b-11e8-87a8-80ff8e24f0ea.jpg)

**Comment by Mark-H** [comment]
That's already switched to lexicons. Perhaps you're seeing cached behavior. Here's what it should look like:

![schermafbeelding 2018-02-12 om 09 49 54](https://user-images.githubusercontent.com/312944/36089057-42952606-0fda-11e8-9f35-646bc6f1b3bc.jpg)

**Comment by rainbowtiger** [comment]
Hmm. Cleared all my caches multiple times. Maybe I missed one of the file updates.

**Comment by rainbowtiger** [comment]
Yup, missed the manager grid file. Updated that, and all is well now. This is great!

**Comment by alroniks** [comment]
Closing as related PR was merged.
