### ISSUE TITLE
add notification of successful database operations on System Info > Database tables

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#3786]
netprophet created Redmine issue ID 3786

Currently, if one of the optimization functions (optimize database, optimize table, truncate event_log table) throws an error, it is reported to the user. There is no confirmation of a successful result.

**Comment by OptimusCrime** [comment]
I think adding that would kind of break the flow.

I can agree that some sort of feedback for optimize database would be nice, but a popup would be rather anoying. It is kind of confusing because after a successful optimization, most of the values in the grid are the same.

Adding a popup to successful truncate event_log does not make much sense. You can clearly see the visual feedback that the log is truncated.

**Comment by rtripault** [comment]
I agree a popup might be more annoying that helpful, but we might consider having a notification, the same way successful resource save shows...

**Comment by alroniks** [comment]
We already have special notification block after saving resources. Why not improve it and reuse for such porpuses?

**Comment by Ibochkarev** [comment]
@Alroniks No need to come up with new solutions when there are working. Simply to improve used

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged.
