### ISSUE TITLE
Preformatted system info for insertion into forums posts and bug reports

### ISSUE THREAD

**Issue by PMS** [modxcms/revolution#3937]
pms created Redmine issue ID 3937

When reporting bugs various system info is required. PHP version, database type and version etc. All that info is already available scattered about on the System Info page. It would be nice if there was a text field that you could copy or a button that you could press that would copy a pre-formatted summary of the basic information required so that it could be easily pasted into bug reports etc.

**Comment by OptimusCrime** [comment]
While this could be useful in some situations I think this is too specific to work into the Modx Core. In almost any case there are just too many factors that play in. Some cases require different information than others. Having just a copy&paste block will not solve that and will in most cases just provide information that is not useful. As this issue is more than 4 years old I suggest closing.

**Comment by pixelchutes** [comment]
I believe with the recent changes in 2.3.x, this support has now been added to better support copy & paste from this page. (See #12261)
