### ISSUE TITLE
modResource::joinGroup fails when numeric string is passed as an ID

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#4014]
jrotering created Redmine issue ID 4014

See forum topic here:

[[http://modxcms.com/forums/index.php/topic,62021.0.html]]

The function is written to take either a name or an ID of a resource group.  It tries to determine whether the passed argument is an ID by testing it with is_int().  This fails on numeric strings.  

I think the options are 

1) leave it as it is and focus on educating end users that if they pass an ID, they have to make sure that it is of type 'integer' and not a numeric string.
2) change the function as I suggested above - the arg will be considered an ID if it passes is_integer and contains only digits.
3) change the function so that it is 'less flexible' - make it require an array for input  "$resource->joinGroup(array('id'=>$id))" or "$resource->joinGroup(array('name'=>$name))"

Additional note - I'm not sure but this may also apply to modUser::joinGroup.  Whatever gets done should probably be consistent throughout all ::joinGroup methods.

**Comment by OptimusCrime** [comment]
This will always be a problem in losely typed languages like PHP is. Solution 1 poses the restriction on the input type. I for one think having the limitation that integer = id and string = name is good enough. Solution 2 will fail in cases where groups are given names with only digits. Solution 3 would be a BC that may be a too big change to swollow.

If I was to redesign this I would not have noe method that handled multiple things, e.i. joining with id and joining with name. A much more clean approach would be to name them something like `joinGroupWithName` or something similar. However, this is too late to introduce now without creating a huge BC in the system.

Because of reasons explained above I am more in favor of having it as it currently is.

**Comment by OptimusCrime** [comment]
One way to "enhancing" the core could be to create the methods `joinGroupWithName` and `joinGroupWithId` to make it easier for developers to use the API.

**Comment by goldsky** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by Mark-H** [comment]
Fixed per https://github.com/modxcms/revolution/commit/773e80d9f0c2e5eb1173ad844c2bcaefc8ee2c87
