### ISSUE TITLE
Groups for contexts

### ISSUE THREAD

**Issue by bravado** [modxcms/revolution#4064]
bravado created Redmine issue ID 4064

For some of my client sites, the number of contexts can get pretty big.  For example, I have one site where the client has a series of single-page sites for each of the 50 American states.  Gets a little ridiculous when you see 50 to 55 different contexts in the manager.  So, what I propose is adding a way where you can group your context into different context "containers".  This would greatly enhance the flexibility of contexts.  Heck, I imagine there's more than one use for this.  :)

**Comment by OptimusCrime** [comment]
I am still in favor of turning this down. Now, someone with the right amount of "authority" has to either agree or disagree to this. 

My reasoning is that context is considered the "topmost" level in MODX as of today. Introducing a new top level will only make things more complicated. Then, some time in the future, somone requests a new level on top of that again. With the flexibility MODX provides, there is always another option to creating 50 contexts for a single page site. I would look into finding another approch rather than implementing the requested feature.

Hopefully someone that can give a final yes or no can adress this and hopefully deal with it accordinly, rather than having this as one of xxxx open isues.

**Comment by rtripault** [comment]
Due to the issue age, and the activity in it, let's go close this one.

On a side note, it is very well possible to build "custom trees" where you could list only the contexts you are interested in. This could very well be released as a third party component.

As usual, feel free to reopen/comment if needed.
Thanks
