### ISSUE TITLE
Group "alias" and "Freeze URI" fields together in Manager

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4379]
ncrossland created Redmine issue ID 4379

"Alias" and "Freeze URI" fields are separate due to legacy / development reasons. Their function is closely related, so it would make sense if they were grouped together in the manager.

**Comment by RinzeVanDerBrug** [comment]
Issue confirmed in 2.5.5. #modxbughunt

**Comment by OptimusCrime** [comment]
This issue is 6 years old and has not gained a lot of traction. I'm more inclined to closing this for reasons @StevenMorgan mentioned. It is true that alias and freeze uri are closely related. However, alias is used in almost every resource, wheras freeze uri may never be used. This will clutter the main interface with options that are not relevant in many cases.

I'm closing this. Feel free to comment or reopen.

@modxbot close
