### ISSUE TITLE
Element Category Access doesn't work properly with templates

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#4475]
Martijn1981 created Redmine issue ID 4475

Here's the situation.
- I made a new category: Secure Elements. (minimum role: Super User, access policy: Element, context: mgr)
- The usergroup Administrator has complete access to this category
- I've now put a template inside that category.

A few things go wrong now.
- When I'm logged in as an admin (as part of the Administrator usergroup) and save a document with that type of tenplate, the name of the template doesn't appear in the dropdown list. Only the ID number.
- And even worse: when I'm logged in as a client (not as an admin), I can't access the Homepage template anymore. Which is what I wanted, thus so far, so good. However, when I open a page which uses that template that I don't have access to anymore, the Template Variables tab is completely gone! It reappears again when I've removed the template from the Secure Elements category.

**Comment by wuuti** [comment]
#modxbughunt 
According to the (very old) forum discussion mentioned above this can be closed. The described behaviour was only there because @Martijn1981 wanted to mimick an Evo ManagerManager behaviour with Revo. The related issue #4441 mentionend in there is also closed. 
I don't see a bug here, so my plea is to close.

**Comment by rtripault** [comment]
Let's go for a close then.

Feel free to comment/reopen if needed.
Thanks
