### ISSUE TITLE
DIRECTORY binding ignores context paths

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#4660]
mindeffects created Redmine issue ID 4660

Hi there,
I have several subdomains, organized in contexts. When I use a TV with a @DIRECTORY binding, I only get the files inside my MODX tree and not of the one, where the context files are stored. To make things clearer, here is my path structure:

<pre>
/cms (MODX)
  /assets
  /connectors
  /core
  /manager
  ...
/sub1 (subdomain1)
  /assets (Assets of subdomain 1)
  config.core.php
  index.php
/sub2 (subdomain2)
  /assets (Assets of subdomain 2)
  config.core.php
  index.php
...
</pre>

That should (hopefully) make my problem (the bug?) clear: Editing a resource in the context "sub2" (same name as the directory) having a template variable with "@DIRECTORY /assets" does not list "/sub2/assets/, it lists "/cms/assets".

**Comment by ilyautkin** [comment]
`@DIRECTORY` binding is relative to the site's root. For list files above root you can use "..":
`@DIRECTORY /../dir_above_root`

This is expected behaviour. More information in documentation: https://docs.modx.com/revolution/2.x/making-sites-with-modx/customizing-content/template-variables/bindings/directory-binding

I think, issue can be closed.
