### ISSUE TITLE
Expand Tree Node When Parent Node Clicked

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#4670]
johnywhy created Redmine issue ID 4670

currently, node only expands if you click arrowhead. 

if parent node itself does not load something into content pane, may as well just expand node for convenience. obviously, user is looking for a child node.

**Comment by OptimusCrime** [comment]
Not 100% sure what you mean by `if parent node itself does not load something into content pane`, but I am going to close this now.

The functionality with the arrow to expand/collapse is by design. Feel free to comment reopen this if you have any further meaning/suggestions, or want to elaborate more.

@modxbot close
