### ISSUE TITLE
Categories cannot contain the ampersand character

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#5658]
netprophet created Redmine issue ID 5658

Steps to reproduce:
- Create a category with the name "Food & Beer"
- Note that the category name drops the & in the Element tree
- Note also that the category name does not contain the & when viewed as a TV tab in Edit Resource

**Comment by OptimusCrime** [comment]
@Mark-H This results in either "by design" or "fix due to incorrect implementation".

Which one makes most sense in this case? I could not fid more issues about the same underlying limitations, but at the same time it makes little to no sense to have this there in the first place. What do you think?

**Comment by wuuti** [comment]
#modxbughunt 

I would plea for by design here. Filtering out the & might have been historically prophylactic to prevent possible problems (maybe with URLs?). If I see that correctly, the same invalid character policy goes for categories and element names. And according to the PHPDoc lines in modcategory it was only copy&pasted there from the modelement. Where it makes sense, I would bet the parser is fucked up with an ampersand in a chunk name. One could argue category names _could_ be less restrictively sanitized, but I don't see an actual need for this, esp. if there _may_ be unexpected sideffects. There are a lot of UTF-8 characters one can use for category names... 
Anyway, as far as the code is concerned, this is by design imho, and definitely not a bug. 
Close?

**Comment by OptimusCrime** [comment]
Good points @wuuti . I am also in favor of closing this.

**Comment by rtripault** [comment]
If i recall correctly there were some issues with ExtJS trees & (non) html encoded entities. Could be one of the reason(s) to this.

Let's close then.

Feel free to comment/reopen if needed.
Thanks
