### ISSUE TITLE
Unable to change label or value of weblink/symlink field with Form Customization on weblinks or symlinks 

### ISSUE THREAD

**Issue by juro** [modxcms/revolution#5700]
juro created Redmine issue ID 5700

FC cannot customize label or default value of "weblink", "symlink" etc field for modWebLink, modSymLink etc resources, because there is no such field in FC rules. Both these fields are in fact written to Content field, but customizing Content doesn't work.

**Comment by iWatchYouFromAfar** [comment]
I tried to reproduce the error. Indeed, it is impossible to set the value of the label. But the default value was successfully established, however, upon transition, the page with identifier 2 did not load, it feels like MODX considers this field empty. The download starts only if you enter the value manually. Screencast I attach below. The problem is still alive.

MODX 2.7.0
PHP 7.2

![unable to change label or value of weblink](https://user-images.githubusercontent.com/16403917/51307547-10eab080-1a51-11e9-9794-43f129dd219a.gif)

**Comment by Ruslan-Aleev** [comment]
In my opinion, we can close this issue.
Fixed in https://github.com/modxcms/revolution/pull/14573

**Comment by Ibochkarev** [comment]
@juro thanks
@modxbot close
