### ISSUE TITLE
stop reloading unnecessary parts of the UI

### ISSUE THREAD

**Issue by gerritvanaaken** [modxcms/revolution#5799]
gerritvanaaken created Redmine issue ID 5799

I made a video that shows the actual MODX manager experience. This is Sparta!

http://screencast.com/t/mcvUPoGzKAi4

Please only refresh those elements that needs to be refreshed! In this case, changing the "boldness" state of the resource titles in page tree would have been enough.

**Comment by Ruslan-Aleev** [comment]
Perhaps the adding additional parameters in the url will allow to clearly define the elements, and not to overload unnecessary. Related to - https://github.com/modxcms/revolution/issues/14086

**Comment by OptimusCrime** [comment]
@Ruslan-Aleev This is not related to browsers putting tabs in sleep. This is what happens when you save a resource or click on a resource in the menu.

However, what the original poster here did not seem to understand, is that the MODX manager is not a single page app, and clicking any links that switches views, will result in a complete page load. This means, that the menu, the topbar, and the main section will all be refreshed.

I am in favor of closing this, as there is no way we are going to make the MODX manager a SPA on this architecture.

**Comment by Ruslan-Aleev** [comment]
@OptimusCrime I'm not talking about browser sleep, but about the fact that if you pass an extra parameter to the url, you can track active elements, and only update it through the script, it seems to me...
But, apparently, I do not quite understand the specifics of single-page applications.

**Comment by JoshuaLuckers** [comment]
Thanks all for taking time to report this issue and make MODX better.
Sadly the screencast is gone, therefore I'm closing this issue.
