### ISSUE TITLE
Provide a means (tag) to fetch http query parameters

### ISSUE THREAD

**Issue by andrazk** [modxcms/revolution#6653]
andrazk created Redmine issue ID 6653

There are many cases, where you send some data via query parameters to the landing page. There's no means to obtain individual parameter values, unless you write a snippet to get the parameters from $_GET['param'].

http://domain.tld/page/request.html?foo=bar

The snippet I use "getParam" looks like this:

return (isset($_GET[$param])) ? $_GET[$param] : '';

And the call [[!getParam? &param=`foo`]] would return "bar"

Basically, while parsing the contents of the document shown, there could be placeholders or a buil-in modifier to provide access to parameter values.

[[?foo]] could return the value "bar". 
Other option could be a built-in modifier, output filter, [[+modx:queryParam=`foo`]]

**Comment by OptimusCrime** [comment]
No further feedback for neither the author nor any MODX core members.

While this is a good idea it poses problems such as security holds as mentioned by @exside. It also looks like this is something people handle by implementing their own snippets/handlers for this.

I am going to close this as a wontfix. Feel free to reopen or comment if you (or anyone else) feel otherwise.

@modxbot close
