### ISSUE TITLE
System Settings not Overridden by Context Settings

### ISSUE THREAD

**Issue by navigator** [modxcms/revolution#7370]
navigator created Redmine issue ID 7370

I'm trying to override the tiny.base_url and the editor_css_path system setting using the context settings so I can have different editor configurations in each site context. The settings are only working at the system setting level.

**Comment by OptimusCrime** [comment]
This is still an issue. Not sure if the problem lies in the Extra or the core.

**Comment by Mark-H** [comment]
It's sort of a feature, not a bug. Grabbing setting values is done with
$modx->getOption  which traverses the various levels of settings, including
the context.

The problem is that while you're in the manager, the current context is set
to "mgr" and not the context the resource is in, as you might expect.

To apply context settings for a resource you'd need to get the working
context and call getOption on that instead. That's something that would
likely need to be done on the extra.
 Op 12 jan. 2015 18:32 schreef "OptimusCrime" <notifications@github.com>:

**Comment by OptimusCrime** [comment]
Makes a lot sense, did not think of that.

Soooo, I guess wontfix?

**Comment by OptimusCrime** [comment]
Closing as wontfix/by design, @Mark-H gave a good explanation why this behavior is correct.

@modxbot close
