### ISSUE TITLE
Can't remove template if set as default for a context 

### ISSUE THREAD

**Issue by MrReaL** [modxcms/revolution#7577]
MrReaL created Redmine issue ID 7577

Made a new context, assigned default_template within context setting with a template. Changed the templated, old template can't be removed because. When removing it says it's in use by [ID] - name. This is also very strange. The context has no visible ID and it shows the first name given to the context, even if the context has changed name during time.

**Comment by rtripault** [comment]
When deleting a `modTemplate`, some checks are done to make sure no resources use the template, nor the template is defined as default template (i'd say system/group/user settings only). So i'd consider this as the expected behavior (see [relevant code](https://github.com/modxcms/revolution/blob/master/core/model/modx/processors/element/template/remove.class.php#L23-39)).

Feel free to comment/reopen if needed.
Thanks
