### ISSUE TITLE
Option to switch user in manager

### ISSUE THREAD

**Issue by DonQuicky** [modxcms/revolution#7612]
donquicky created Redmine issue ID 7612

It can be very handy for admins to switch to other user in manager with option to switch back without having logging off as admin. In the situation of testing access rights of users this option would be very handy. In other CMS-systems I use this function very often.

**Comment by adamwintle** [comment]
I spotted this today, it looks like it handles quick user switching for testing, etc (I haven't tried it myself yet) https://modstore.pro/packages/users/switchuser

**Comment by OptimusCrime** [comment]
Looks like many issues can be closed as a "Solved by extra". I like the idea of a slim MODx core and introduce various custom functionality with extras instead.

What do you guys think?

**Comment by adamwintle** [comment]
I'm with @OptimusCrime on this one, I think the MODX core should be as lightweight as possible and then extended via plugins. So if any plugins have been created (especially since some of these old issues were opened in 2008-2015) then we should close them in favour of using the plugin.

Especially the features are not on any roadmaps and the issues have been open >2 years.

However saying that there was one issue related to proper previews in MODX (https://github.com/modxcms/revolution/issues/4154) that @rthrash stepped in and mentioned he'd like to keep that particular case open, as a core previews feature may be imlimented in the future. 

So although I'd like to add something to the guidelines for "Close if solved by extra"; we'll have to take them case-by-case for now.

**Comment by OptimusCrime** [comment]
I agree with that :)

**Comment by DonQuicky** [comment]
Clear arguments. Thanks !!
