### ISSUE TITLE
MODX_CORE_PATH sometimes malformed on windows

### ISSUE THREAD

**Issue by feamsr00** [modxcms/revolution#8076]
feamsr00 created Redmine issue ID 8076

Sometimes during an advanced install MODX_CORE_PATH will not be stored with a trailing slash, thus causing the conditions in findCore (source:setup/includes/modinstall.class.php@436606b3732008b593cb5ea1bccf80d2c05ebd8f#L785) to fail.

**Comment by OptimusCrime** [comment]
"Sometimes" is kind of hard to test or try to reproduce. I do not have a Windows env that I can run this on, but I guess there would be more reports if this was a major issue for all Windows installations.

Might be an isolated incidence.

Closing ticket because of age and lack of further information. Feel free to reopen if this is still an issue.

@modxbot close

**Comment by feamsr00** [comment]
I think that's fair. MODX *was* a bit flaky on windows hosts. I'm pleased to report that's its been more stable as late. Although, I would still ask for unit (or some such) tests that could easily help root out such "intermittent failures"

**Comment by OptimusCrime** [comment]
Great, thanks for following up on this @feamsr00 :)

And yeah, we all agree, there should be a test suit for revo. I thiiiiiink people might be working on something there.
