### ISSUE TITLE
Form Customization Errors

### ISSUE THREAD

**Issue by darwin** [modxcms/revolution#8187]
darwin created Redmine issue ID 8187

I was getting this in form Customization. I talked with Bob Ray and he wanted me to file this as a bug.

Notice: Undefined index: /../../../security/forms/set/update.class.php on line 96
Notice: Undefined index: /../../../security/forms/set/update.class.php on line 95

He said the problem was with:
if (!empty($field['label'])) {

and that it should be:
if (isset($field['label']) && !empty($field['label'])) {

**Comment by OptimusCrime** [comment]
I am not able to reproduce this in my logs. There are no notices getting logged here. It is somewhat likely that this might have been fixed since it was filed. I can see lines [93-94](https://github.com/modxcms/revolution/blob/2.x/manager/controllers/default/security/forms/set/update.class.php#L93-94) are testing for value before being accessed. This might be a fix for the problem here.

Closing this due to age and lack of activity. Feel free to reopen if this is still an issue or you have more details that can help us further.

@modxbot close
