### ISSUE TITLE
Stop storing snippets and plugins in the database

### ISSUE THREAD

**Issue by robincafolla** [modxcms/revolution#8335]
thelastshadow created Redmine issue ID 8335

As modx caches snippets and plugins why bother storing them in the database?

Every other cms allows developers to write php code to a server via ssh or ftp and have the cms execute that code. Even with static resources in modx you have to clear the cache through the panel, or hunt down numbered cache files and delete them via ftp.

In terms of convenience, anyone who is editing snippets and plug-ins knows PHP, which means they almost certainly know how to ftp to a server to make those changes. I would argue that it is more convenient being able to edit code in the IDE or editor you are familiar with than it is to be able to edit those files via the manager.

Even if you did remove the files from the database the manager could still edit the files if they had write access. This would be a bit insecure, but no more so than the static resources currently are.

**Comment by rainbowtiger** [comment]
My main objection to permanently detaching snippets from the database is that they will no longer get saved in VersionX. I set all of my snippets to be static, so that I can develop them locally and then just upload them, and this works great. But in cases where I have to work with another developer remotely, it gives the option of having that person edit directly in MODX, recording all updates in the versioning system there, and then I just periodically go into MODX and hit the Save button for a snippet after I've done a round of edits locally and then uploaded that I want to keep a record of online. This lets VersionX be the source of versioning for all programmers involved in the project. Of course, I have to remember to always download a copy of the snippet to make sure I have any updates the external programmer may have made, and this requires good communication to be in place so everyone knows what everyone else is working on. So the versioning is fully automatic, but it works. Removing snippets from the database wouldn't give us any capability we don't already have, and would actually reduce the flexibility in how people can manage snippets.

**Comment by Mark-H** [comment]
VersionX developer here :D in your situation, a git workflow might be more appropriate. 

Storing stuff in the file system also doesn't mean it can't also be editable in a manager. That could just write to a file instead of a database.

**Comment by SebastienDaniel** [comment]
I second @Mark-H on that, what you described, @rainbowtiger is definitely a versioning system setup (*git, mercurial, etc.*).

I'd also argue that most developers are more comfortable editing code in their editor/IDE of choice rather than the MODx interface. A proper versioning workflow wont impose MODx on them.

**Comment by Mark-H** [comment]
I personally do tend to use the manager for lots of quick things, so I'm not advocating for forcing git and IDEs on everyone. Lots of projects aren't complex enough to absolutely need that.

**Comment by rainbowtiger** [comment]
the other programmers I tend to work with aren't on github, so it's not worth the effort for me to set up something like that.

**Comment by robincafolla** [comment]
tbh it's been a very long time since I built anything in modx, so I have no idea what the current CMS is capable of. That said, it amazes me that nearly 4 years later this feature hasn't been added.

In 2012 all serious developers used version control. In 2016 the idea that a dev wouldn't use git or mercurial to track code versions is absurd. The idea that you would need to write PHP code to a DB is bizarre.

There were things modx got right when I used it all those years ago, but I'd never recommend it to a developer, because it was awful to build websites with. Ultimately if you can't convert devs, good luck building a community.

**Comment by rainbowtiger** [comment]
Well, I don't agree with this at all. You're free to use github or mercurial or whatever you want for versioning, and upload files to MODX, where it will use those static files for the snippets. You're free to use whatever versioning system you like, and I'm free to use whatever I like. MODX will adapt to whatever setup you use. That's exactly why it's great for building websites. I can even build an AngularJS site with it if I want. That's how flexible it is.

**Comment by JimKillock** [comment]
We use MODX at openrightsgroup.org and this is certainly a barrier to us expanding our pool of volunteer developers - it may in the end be a key reason we move away from MODX if  MODX continues to be somewhat awkward to use with Git etc; if it seemed to play more naturally with versioning tools I am sure that would be an advantage.

**Comment by rainbowtiger** [comment]
The developers I have occasionally reached out to when in need to additional programming assistance have had zero problems quickly adapting to how MODX works, even with no experience with it whatsoever.

**Comment by Mark-H** [comment]
Jim, have you looked into Gitify before? Might suit your needs.

Any suggestions on a better implementation? Dropping the snippets table isn't that hard to do, but obviously that's not the full story here, and I'm much more interested in what should happen after that.

**Comment by jpdevries** [comment]
> I personally do tend to use the manager for lots of quick things, so I'm not advocating for forcing git and IDEs on everyone. Lots of projects aren't complex enough to absolutely need that.

I agree. But I also lean towards keeping elements out of the db in the future – as in MODX Next. I feel like the manager can still provide all the pros, like in manager editing of elements, while still keeping elements on the file system. I think this one can be a win-win.

**Comment by Mark-H** [comment]
This is not going to be a feasible change in the near future so I'm going to close the issue. I know there are ideas about it floating around here and there though, so when we get round to breaking changes perhaps we'll see something like this.
