### ISSUE TITLE
File Browser allows silent overwriting of files

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#8371]
MokoJumbie created Redmine issue ID 8371

The File Browser should notify you if a file will be overwritten when uploading files. Currently, a file can be overwritten on upload without even a warning.

**Comment by RinzeVanDerBrug** [comment]
Going to test this today.

**Comment by RinzeVanDerBrug** [comment]
Able to reproduce this.

Tested this in MODX 2.5.5. When uploading a file with a name which already exists in the file manager, the system will tell you your upload was successful. When you refresh the file manager afterwards, you'll see that the existing file is still there and the file you uploaded 'successfully' is nowhere to be found. 
![image](https://cloud.githubusercontent.com/assets/25863377/23552441/269f6048-001c-11e7-8087-f2a7b5355618.png)

Confirmed. #modxbughunt

**Comment by meshkov** [comment]
Tested it in MODX 3.0 and it is still actual for MODX 3.0.
And actual for drag&drop packages in package manager. 
You can see also on the demo in #13851

**Comment by iWatchYouFromAfar** [comment]
This problem is very relevant so far. Almost on all sites that i create, i have to make image renaming plugins to avoid duplicate names. At the same time, silent renaming does not work if you rename a file already uploaded to the server. 

I reproduced on the current dev branch MODX 3.x. Any ideas for fixing this problem?
![file-browser](https://user-images.githubusercontent.com/16403917/51986356-1f08ea00-24b1-11e9-9cf3-66e95b67e84e.gif)

**Comment by sebastian-marinescu** [comment]
Silently overwriting doesn't seem good. A confirmation of overwriting the file would be the best UX here.

**Comment by pyrographics** [comment]
Rather than failing to upload or overwriting a file it should add _1, _2, _3 or similar to the filename of the duplicates.  This is what most browser downloads do.

**Comment by Ibochkarev** [comment]
Improved in #15232 

@modxbot close
