### ISSUE TITLE
Option to switch to "standard mode" when using Form Customised resources

### ISSUE THREAD

**Issue by paulkoan** [modxcms/revolution#8406]
paulkoan created Redmine issue ID 8406

Form customisation lets administrators provide a specific view of a resource with a specific set of fields and tab layout.  

This is useful when providing access to content editors that do not ordinarily need to see the full set of options when editing content.

In the example of a blog entry, this can be slimmed down to Title, Summary and Content, for example, and is a much more appealing, less daunting interface.

However, on occasion, the user may need to do something more complex, and so want the "standard" view to access the additional fields.  The only way to achieve this currently is to provide a second account that would be used on these occasions.

This feature request is to add a checkbox or similar that allows the user to switch between the focussed form customised view and the standard view as needed - essentially using the form customisation as a convenience rather than a security feature.

**Comment by OptimusCrime** [comment]
This issue is very old and there has been no interest around this since it was posted. If I understand the issue correctly, you want both to hide fields using FC, while also allowing a toggle to hide the fields that were hidden. I find this counter counterintuitive. If the "advanced" fields needs to be visible sometimes, just move it to another tab and let them live there. I am closing this issue. Feel free to reopen it or comment.

**Comment by OptimusCrime** [comment]
@modxbot close
