### ISSUE TITLE
Template Variables in a sub category not visible to editors

### ISSUE THREAD

**Issue by TimGS** [modxcms/revolution#8511]
timgs created Redmine issue ID 8511

Probably the same as http://forums.modx.com/thread/78547/potential-bug---can-t-see-certain-template-variables-help, but I can't see that having been reported on here. Apologies if it has and I'm duplicating an issue.

TVs in a sub-category (depth = 2) are invisible to Content Editors. Moving the sub-category out of its parent and into the 'root' is sufficient to make the TVs available to editors. 

Administrator accounts unaffected.

**Comment by gernotebenlechner** [comment]
Just checked this issue at the #modxbughunt on a clean 2.5.8-dev install with a non-"Sudo user" user with the default "Content Editor" access policy assigned. 

Result: I **this issue is NOT CONFIRMED**: even TVs in the third sub-category (depth = 3) can be seen and edited by the content editor user (see screenshots).

![8511a](https://user-images.githubusercontent.com/6340951/27953149-09a48d0e-630b-11e7-8877-b41e94ef5d4e.gif)

![8511b](https://user-images.githubusercontent.com/6340951/27953160-0fb739bc-630b-11e7-9f5c-3e9e9bd3fc53.gif)

**Comment by rtripault** [comment]
Thanks @gernotebenlechner so closing that one.

Please feel free to comment/reopen if needed.
Thanks

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @gernotebenlechner
