### ISSUE TITLE
Manager login language setting ignored

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#9073]
mindeffects created Redmine issue ID 9073

The manager login give me the option to select a language but ignores this setting once I am logged in. Bug? Or am I missing something?

best
Oliver

**Comment by Alroniks** [comment]
Will fix it #modxbughunt

**Comment by OptimusCrime** [comment]
@Alroniks did you ever finish your PR?

**Comment by Alroniks** [comment]
@OptimusCrime Not yet. I tried but it is not so easy as I thought at the start. I don't remember exactly what problems I met but it needs more attention. But feature may be very useful. Because now for change language of the manager you have to use different logins or change system settings after of before every login.

**Comment by alroniks** [comment]
I am closing it because in 3.x this part was redone and now works as expected.
