### ISSUE TITLE
Option to eliminate "empty Template" from drop-down list.

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#9558]
bobray created Redmine issue ID 9558

This request is to provide a way to hide or remove the "empty Template" option from the drop-down list when selecting a Template on the Create/Edit Resource panel.

There are cases where you don't want to allow users to select the empty template and, at present, no way to do that.

The drop-down list is created on-the-fly with ExtJS so it's difficult to modify it.

**Comment by RinzeVanDerBrug** [comment]
Issue is still present in MODX 2.5.5. #modxbughunt

**Comment by OptimusCrime** [comment]
Hmm. I am not 100% sure why you would want a feature like this. And how is it going to work? If it is a system setting it would happen across the board, affecting every resource. If there are some resource that you'd like to have no template and others where this is hidden you would get either or in this scenario.

Otherwise, if you'd like to have this applied to only some resources it would have to be a setting that can be toggled in the create/edit resource view. This removes the purpose as you could easily just change that and set the template to empty.

Also, this was reported in 2013, and has not seen any interest from other users.

**Comment by BobRay** [comment]
I can imagine cases where you wouldn't want naive users to apply the empty template thinking it was a good starting point.

If it were a permission (show_empty_template), it could be applied to selected resources when accessed by specific users.

A simpler solution would be to make it a System Setting that didn't affect to sudo users.

That said, it's not something I think is critical.

**Comment by OptimusCrime** [comment]
This feature request have seen no interest since 2013. I am going to close it. Feel free to reopen or comment.

@modxbot close
