### ISSUE TITLE
$object->clearCache() convenience method

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#9559]
bobray created Redmine issue ID 9559

The code for clearing the cache for a single resource or script is pretty daunting (and often doesn't seem to work for me). 

People are calling refresh() and clearing the whole site cache when they just want a small change to a snippet or resource to take effect because they can't figure out, or can't remember, how to use refresh() for that.

Usually, you already have the object in question, so calling $object->clearCache() would be really handy.

**Comment by Mark-H** [comment]
`refresh()` has a property to specify what partitions to clear. 

There's also `$resource->clearCache()`. Clearing scripts is not as easy, because they're also cached with the resource in the elementCache, so you'd need to wipe both the resources and the element cache. Hence why a cache clear wipes more than just one partition or file for that kind of thing.

**Comment by BobRay** [comment]
I don't think $resource->cllearCache() existed when I filed this.

**Comment by Mark-H** [comment]
That's entirely possible :D
